### ISSUE TITLE
How does sgx-lkl support multi-process applications?

### ISSUE THREAD

**Issue by tatetian** [lsds/sgx-lkl#1]
I am excited to see a new, open-source library OS for SGX. Good job on supporting JVM on SGX.

Before sgx-lkl, the only open-source alternative is Graphene-SGX, which puts an emphasis on its support for multi-process applications. So, I am wondering **how sgx-lkl supports multi-process applications**.

I am asking this question because there seems to be a dilemma: all processes must share a common Linux kernel (i.e. LKL), which means different processes must run in the same enclave, **thus leading to no isolation between processes**. Is my understanding right?

Thanks.

**Comment by prp** [comment]
Thanks for your interest. Currently SGX-LKL doesn't support multi-process applications. As you say, one option would be to execute multiple processes in the same enclave address space, but this would offer no protection. Alternatively, each process could obtain its own address space with a separate enclave, but it is hard to see how this could be implemented without a substantial performance overhead.

We didn't find the restriction of only supporting a single process too restrictive. Our focus so far has been on multi-threaded and not multi-process applications.

**Comment by tatetian** [comment]
I see. Thanks for explaining :)
