### ISSUE TITLE
Suggest attestation details from the FAQ Docs 

### ISSUE THREAD

**Issue by agowdamsft** [lsds/sgx-lkl#102]
For the current open source release attestation is not part of it and should be reworded or removed "Can I use a Confidential Linux Container on a normal Linux system?"

**Comment by elianavan028** [comment]
verwijzend naar een leuk artikel, bedankt voor een geweldig artikel. Het heeft me veel geholpen. Ga zo door Must Visit: [Avast klantenservice nummer](https://techhelpnumber.com/avast-antivirus-klantenservice-belgie.html) .
