### ISSUE TITLE
[Build] Should OE be built as a submodule of SGX-LKL 

### ISSUE THREAD

**Issue by jhand2** [lsds/sgx-lkl#105]
Currently OE is included from its install location (/opt/openenclave) and the expectation is that it was previously installed on the machine on which SGX-LKL is being built.

OE should be included as a submodule of SGX-LKL and built as part of the SGX-LKL build process similar to other dependencies such as musl and lkl.

Please know that until this is done, SGX-LKL might break with no warning any time OE changes. Breaking changes are announced by OE on a release cycle but depending on the tip of master gives very few stability guarantees for a pre1.0 project.

**Comment by prp** [comment]
I would like to revive the discussion if we should build the SGX-LKL fork of OE as a submodule of SGX-LKL. I think that it would make building more user-friendly and less error-prone while we are using a version of OE that isn't master. If we make this change, we just need to ensure that this will remain compatible with future modifications of the build system.

cc: @paulcallen @davidchisnall @letmaik @wintersteiger @jxyang

**Comment by letmaik** [comment]
Makes sense to me. As long as we add a build option like OE_PREFIX to optionally pick up an already installed OE it should cover all dev use cases.

**Comment by wintersteiger** [comment]
Yeah, I agree; we need `OE_PREFIX` to override the path when necessary, but in general I think it's a good idea, at least until we depend on OE master instead of our own branches.

**Comment by prp** [comment]
Fixed by #423
