### ISSUE TITLE
What is `src/libsgx/libs/{lible.a, lible.so}`?

### ISSUE THREAD

**Issue by mssun** [lsds/sgx-lkl#12]
I guess it is the launch enclave, but I didn't find any source code for generating the `lible`.

**Comment by cpriebe** [comment]
Hi Bob,

thanks for opening this issue! They are just wrappers around (an older version of) the Intel-provided launch enclave. We should switch to simply use the LE that comes with the Intel PSW. We'll look into that and push a corresponding change soon.

**Comment by mssun** [comment]
Got it. Thank you!
-- 
Best,
Mingshen
www.cse.cuhk.edu.hk/~mssun
