### ISSUE TITLE
Enclave Timing is Incorrect

### ISSUE THREAD

**Issue by praenubilus** [lsds/sgx-lkl#121]
We have found time issue in sgxlkl oe_port branch.
The symptom: when starting enclave, the system time in the enclave will be set to 
**Thu Jan  1 00:00:00 UTC 1970**
@jxyang can verify that.

**Comment by SeanTAllen** [comment]
This is probably because https://github.com/lsds/sgx-lkl-musl-oe/pull/30 was moved over and the sgx-lkl work required to make that a reasonable change is currently hung up on some issue (I'm currently working on it).

Adding that change back in the syscall.h should fix the issue.

**Comment by SeanTAllen** [comment]
@jxyang is currently confirming the fix for this.

**Comment by jxyang** [comment]
Yes, the fix enabled the ocall workaround and the timing is correct now.

**Comment by SeanTAllen** [comment]
@prp can you close this issue? I don't have permissions to close.

**Comment by hukoyu** [comment]
How is this fixed? I don't see the related PR.

**Comment by jxyang** [comment]
This is the PR: https://github.com/lsds/sgx-lkl/pull/126

**Comment by hukoyu** [comment]
This issue still exists. Issue https://github.com/lsds/sgx-lkl/issues/157 created since we cannot reopen this issue.
