### ISSUE TITLE
"Test Plans" is not enabled for sgx-lkl CI pipeline

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#128]
In the Azure DevOps CI pipeline  https://dev.azure.com/sgx-lkl/sgx-lkl "Test Plans" is not enabled.
"Test Plans" should be enabled so that 
1) we can see test runs
2) In the pipeline job in "Publish Test Results" the link to test run can be used. Now it gives 404

![image](https://user-images.githubusercontent.com/61761684/80770668-b53d1d00-8b05-11ea-882b-05ae287973c6.png)

Sample pipeline run:
https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=48&view=logs&j=52da39ca-12fd-51a2-9e72-fb308494e810
 
![image](https://user-images.githubusercontent.com/61761684/80770782-17961d80-8b06-11ea-88e4-ddbd83fdbb1c.png)

when clicked the link for test result we get 404
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=200&_a=runCharts

**Comment by hukoyu** [comment]
@letmaik we need to enable "Test Plans" in pipeline to see test runs and be able to use test result links.

**Comment by letmaik** [comment]
I don't think we need this. Can you check if the following works?

![grafik](https://user-images.githubusercontent.com/530988/80787605-dc840080-8b7e-11ea-8b8a-e42c3942f0ac.png)

![grafik](https://user-images.githubusercontent.com/530988/80787673-105f2600-8b7f-11ea-8e36-ca69314fad1c.png)

**Comment by letmaik** [comment]
Anyway, I enabled it now, even though I think it's not needed really. But maybe I'm missing something?

**Comment by hukoyu** [comment]
Now links are working properly. Yes this summary test result is also working but test result pages are more user friendly.
