### ISSUE TITLE
Remote attestation

### ISSUE THREAD

**Issue by mssun** [lsds/sgx-lkl#13]
This is an amazing project. However, I didn't find any support for remote attestation (including other projects like `libSEAL` and `TaLoS` based on some components of `sgx-lkl`). Remote attestation (or attestation) is one of the most essential feature of SGX.

Do you have any plan on this? Or, is there any implementation challenges on the attestation? I found you are developing some building blocks similar with Intel SGX PSW, so I guess the Quoting Enclave should be also included. Anyway, I would like to hear your plan on this. Thank you so much.

**Comment by cpriebe** [comment]
Agreed. Remote attestation definitely is an essential feature. Intel has actually done some work on remote attestation for SGX-LKL via TLS which you can find here: https://github.com/cloud-security-research/sgx-ra-tls

However, we are working on fully integrating remote attestation into SGX-LKL too, and hopefully will have something ready within the next month or so.

**Comment by dimakuv** [comment]
Ping. Curious about the current status of remote attestation support.

**Comment by cpriebe** [comment]
We do have an internal working implementation. It still needs some work (clean up) but should make it into this repository pretty soon.

**Comment by mygithubsunny** [comment]
what is the current status of remote attestation support? any progress?

**Comment by cpriebe** [comment]
Apologies for the late response. I am hopeful we can push some initial (remote) attestation support within the next week or so.

**Comment by cpriebe** [comment]
We have now added remote attestation capabilities. They are described here in detail: https://github.com/lsds/sgx-lkl/wiki/Remote-Attestation-and-Remote-Control

I'm sure this does not cover all use cases, so feel free to open a new issue for specific requests. I will close this issue for now. if there are any questions regarding the existing implementation and/or how to use it, it probably makes sense to open a new issue as well.
