### ISSUE TITLE
Add shared page to replace brittle VDSO mechanism

### ISSUE THREAD

**Issue by SeanTAllen** [lsds/sgx-lkl#134]
Currently the VDSO support in SGX-LKL is brittle and fails with particular versions of the host Linux kernel. This may break VDSO time-related calls, e.g. in Python, which fails with incorrect timestamps. (In such cases, the VDSO support can be deactivated with SGXLKL_GETTIME_VDSO=0 but this adds a substantial performance penalty.)

VDSO support is specifically broken in Linux 5.0 kernels. 

The problem with the VSDO approach is that it is brittle and has to be updated for different versions of the kernel. Continuing with the current approach would mean a series of patches for multiple Linux kernel versions and a continually growing maintenance headache.

@davidchisnall came up with the idea to use memory shared between the host and the enclave to provide an in-enclave source of nano ticks that is powered by a thread that runs outside the enclave. The outside thread will, on a regular basis, update a data structure in shared memory to denote the passage of time outside the enclave. 

This can then be used inside the enclave to power a monotonic counter that will be inserted into the Linux architecture layer to supply a source of monotonic time. Linux uses that source to drive other clocks like CLOCK_REALTIME. 

When work is completed on this, a new issue can be opened to remove the old VSDO support which @prp turned off as a workaround.

**Comment by SeanTAllen** [comment]
PR is open for this that addresses this. There's a couple changes that can/should be made to it, but this is done from a functionality standpoint and will be merged soon.

https://github.com/lsds/sgx-lkl/pull/162

**Comment by prp** [comment]
@SeanTAllen can we now remove all dead code related to the old VDSO mechanism, e.g.: https://github.com/lsds/sgx-lkl/blob/a4fc0cc6fea39f30d33783e55626afbff3c7a871/src/main/sgxlkl_run.c#L758, https://github.com/lsds/sgx-lkl/blob/5bb8a20a9567e7c2a77bf64957201704a3ca0545/src/main-oe/sgxlkl_params.c#L89 etc. Thanks.

**Comment by SeanTAllen** [comment]
When can @prp. Can you open an issue for that and assign me?
