### ISSUE TITLE
The value of file descriptor is always zero for all the files inside enclave.

### ISSUE THREAD

**Issue by vamsikrishna935** [lsds/sgx-lkl#143]
Created a three files and assigned file descriptor variables to each. All the file descriptor values are zero.

TestCase: Open13
Debugging details:
Thread 6 "ENCLAVE" hit Breakpoint 2, main (ac=<optimized out>, av=<optimized out>) at open13.c:86
86      in open13.c
(gdb) p fd
$1 = 0
(gdb) p fd2
$2 = 0
(gdb) p fd1
$3 = 0

Use the below patch code for creating files and verifying the values.
diff --git a/testcases/kernel/syscalls/open/open13.c b/testcases/kernel/syscalls/open/open13.c
index 3838221e1..2848f7f67 100644
--- a/testcases/kernel/syscalls/open/open13.c
+++ b/testcases/kernel/syscalls/open/open13.c
@@ -40,6 +40,9 @@
 #include "lapi/fcntl.h"
 
 #define TESTFILE	"testfile"
+#define TESTFILE1        "testfile1"
+#define TESTFILE2        "testfile2"
+
 #define FILE_MODE	(S_IRWXU | S_IRWXG | S_IRWXO | S_ISUID | S_ISGID)
 
 static void setup(void);
@@ -53,7 +56,7 @@ static void verify_fgetxattr(void);
 static void check_result(const char *call_name);
 static void cleanup(void);
 
-static int fd;
+static int fd, fd1, fd2;
 
 static void (*test_func[])(void) = {
 	verify_read,
@@ -80,12 +83,15 @@ int main(int ac, char **av)
 	for (lc = 0; TEST_LOOPING(lc); lc++) {
 		tst_count = 0;
 
-		fd = SAFE_OPEN(cleanup, TESTFILE, O_RDWR | O_PATH);
-
+		fd = SAFE_OPEN(cleanup, TESTFILE, O_PATH);
+		fd1 = SAFE_OPEN(cleanup, TESTFILE1, O_PATH);
+		fd2 = SAFE_OPEN(cleanup, TESTFILE2, O_PATH);
 		for (tc = 0; tc < TST_TOTAL; tc++)
 			(*test_func[tc])();
 
 		SAFE_CLOSE(cleanup, fd);
+		SAFE_CLOSE(cleanup, fd1);
+		SAFE_CLOSE(cleanup, fd2);
 		fd = 0;
 	}
 
@@ -105,6 +111,8 @@ static void setup(void)
 	tst_tmpdir();
 
 	SAFE_TOUCH(cleanup, TESTFILE, FILE_MODE, NULL);
+	SAFE_TOUCH(cleanup, TESTFILE1, FILE_MODE, NULL);
+	SAFE_TOUCH(cleanup, TESTFILE2, FILE_MODE, NULL);
 
 	TEST_PAUSE;
 }
@@ -113,32 +121,32 @@ static void verify_read(void)
 {
 	char buf[255];
 
-	TEST(read(fd, buf, sizeof(buf)));
+	TEST(read(fd2, buf, sizeof(buf)));
 	check_result("read(2)");
 }
 
 static void verify_write(void)
 {
-	TEST(write(fd, "w", 1));
+	TEST(write(fd2, "w", 1));
 	check_result("write(2)");
 }
 
 static void verify_fchmod(void)
 {
-	TEST(fchmod(fd, 0666));
+	TEST(fchmod(fd2, 0666));
 	check_result("fchmod(2)");
 }
 
 static void verify_fchown(void)
 {
-	TEST(fchown(fd, 1000, 1000));
+	TEST(fchown(fd2, 1000, 1000));
 	check_result("fchown(2)");
 }
 
 #ifdef HAVE_SYS_XATTR_H
 static void verify_fgetxattr(void)
 {
-	TEST(fgetxattr(fd, "tkey", NULL, 1));
+	TEST(fgetxattr(fd2, "tkey", NULL, 1));
 	check_result("fgetxattr(2)");
 }
 #endif

**Comment by hukoyu** [comment]
This sgx-lkl product bug found while trying to fix LTP test kernel/syscalls/open/open13

**Comment by vamsikrishna935** [comment]
@prp : Found product bug while fixing ltp test open13

**Comment by vamsikrishna935** [comment]
Issue does not repro's in latest oe_port branch. Hence closing the issue.
