### ISSUE TITLE
Fix the root cause of flaky test failures and enable disabled non-ltp tests

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#147]
We added mechanism to be able to disable a non-ltp test by adding Makefile path to this file: https://github.com/lsds/sgx-lkl/blob/oe_port/.azure-pipelines/scripts/disabled_tests.txt

For now we disabled these tests since they were failing randomly and causing pipeline fail. We disabled these tests until the root cause of falure(s) found and fixed.

We should fix these tests and enable by removing from this disabled_tests.txt
In the "Run Test" task of build jobs we have disabled tests reported. Our target must be 0 disabled reported there. Creating this issue so that we don't forget these disabled tests.

**Comment by letmaik** [comment]
I think having a generic issue like this doesn't help much. Why don't we create separate issues for each disabled test? Then it's also easier to search for it etc.

**Comment by hukoyu** [comment]
I aggree. This issue is too generic. Closing this one and will create specific issues when needed.

**Comment by letmaik** [comment]
@hukoyu Please don't forget this. There are no issues for all the disabled tests and we are not noticing any regressions currently. Why don't we run the tests at least during the nightly builds?

**Comment by SeanTAllen** [comment]
I think that a nightly run of "flakey" test would be great. Especially if we have an easy means to which are no longer flakey.
