### ISSUE TITLE
Non-zero exit codes ignored in LTP tests

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#148]
When an LTP test exits with non-zero exit code (e.g. due to a segfault) then this is not captured. The current logic only scans through stdout/stderr, but doesn't look at exit codes. The only reason we still observe faults like that at all is that the upper level test runner scans the output of the ltp test "test suite" and would find "Segmentation fault" in it, but then it is impossible to figure out which LTP test failed since all are marked as passing.

run_ltp_test.sh should be extended to contain the same exit code logic as run_test.sh

@hukoyu

**Comment by hukoyu** [comment]
@letmaik as seen here https://github.com/lsds/sgx-lkl/blob/oe_port/tests/ltp/run_ltp_test.sh#L97-L100
For an LTP test to pass it must have "PASS" in its logs. You mean an LTP test is getting Segmentation fault and also have PASS/PASSED in its logs? Since when it gets segmentation fault it shouldn't be able to output PASS/PASSED to its logs which will cause this test to be marked as FAILED as well as ltp-batch1-(debug) as well (for the whole suit). Do you have a sample proving your theory that ltp test suite fails due to segmentation fault and all ltp tests passed?

**Comment by letmaik** [comment]
@hukoyu Are you sure the test has to output PASS/PASSED? I could only find the failure identifiers in the run_ltp_test.sh.

**Comment by letmaik** [comment]
Here's a sample: https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=183&view=ms.vss-test-web.build-test-results-tab None of the ltp tests is marked as failed, only the overall result.

**Comment by letmaik** [comment]
@hukoyu I think the bug is in this line: https://github.com/lsds/sgx-lkl/blob/83c1342e8d9d28e4ee2b2dc0bd9e8e52316a0bb2/tests/ltp/run_ltp_test.sh#L97 For some reason there's an "i" at the end which would mean `$pass_count ==  0` never succeeds.

**Comment by letmaik** [comment]
There are other bugs there as well:
https://github.com/lsds/sgx-lkl/blob/83c1342e8d9d28e4ee2b2dc0bd9e8e52316a0bb2/tests/ltp/run_ltp_test.sh#L101

`if [[ $total_failures == 0 && $pass_count > 0 ]]` doesn't make any sense. Bash would see `>` as file redirection.

Could someone take a pass over this file please?

**Comment by hukoyu** [comment]
@letmaik you are right, i is stayed there by mistake (I think i for insert mode in vim)
I will submit a PR for removing i and fixing greater than issues.

**Comment by letmaik** [comment]
@hukoyu Could you check whether it's true in general that LTP tests return a non-zero exit code if there's a failure and zero if they pass? If that's the case then we could remove all the string matching logic and simply rely on that. Checking for non-zero would then also catch other unexpected issues like segfaults.

**Comment by hukoyu** [comment]
This is fixed with PR https://github.com/lsds/sgx-lkl/pull/294
