### ISSUE TITLE
Merge LTP1 and LPT2 test suites

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#168]
Each LTP test job (one configuration, e.g. debug hw) takes 2-3min (only the testing step, not the rest). I propose merging the LTP1 and LTP2 suites into one to avoid having overhead from job creation itself. The runtime would then be 4-6min per LTP test job.

**Comment by jxyang** [comment]
Each LTP batch takes about half an hour. I am not clear what you are proposing.

**Comment by hukoyu** [comment]
I didn't understand this issue. LTP tests splitted into 2 batches so that can be run in parallel for a shorter pipeline run time. There are 440 LTP tests and each suite runs 220 LTP tests. Aslo didn;t understand 2-3 min since it takes around 30 minutes each LTP tests job. Am I misunderstanding the target in this issue?

**Comment by letmaik** [comment]
Sorry I should have said this is with the re-designed CI. Have a look at https://dev.azure.com/sgx-lkl/ff25f828-9f87-48e4-94f0-7449609f7e8f/_build/results?buildId=167

**Comment by hukoyu** [comment]
> Sorry I should have said this is with the re-designed CI. Have a look at https://dev.azure.com/sgx-lkl/ff25f828-9f87-48e4-94f0-7449609f7e8f/_build/results?buildId=167

@letmaik  I checked the CI pipeline link you shared. It says for example ltp-batch1 debug hw tests run in 2-3 minutes. I don't think this is true. Also I checked test result https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=946&_a=resultQuery and test durations are zero. 

Are you planning to run ltp tests for both debug and non-debug? Also both hw and sw. Currently we are running debug and hw only. Running them with all combinations will require 4 times resources or 4 times longer.

**Comment by hukoyu** [comment]
@letmaik if you look at the test results zip file for the test suite you will see junit test xml file is similar for all tests and it has this info:
```<testsuites>
  <testsuite name="Default">
    <testcase name="kernel-syscalls-accept-accept01-(debug)-(run-hw)" classname="ltp" time="0">
      <system-out></system-out>
      <system-err>timeout: failed to run command â€˜/agent/_work/1/s/build/sgx-lkl-run-oeâ€™: No such file or directory</system-err>
    </testcase>
  </testsuite>
</testsuites>
```
TestResults_946.zip in the attachments here https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=946&_a=runCharts

**Comment by letmaik** [comment]
Thanks, I'll fix that. I wonder why the tests don't appear as failed though. Probably the same issue as #148.

**Comment by letmaik** [comment]
Fix is up at https://github.com/lsds/sgx-lkl/pull/173. I guess we can close this issue since the tests won't in fact run as fast as I thought.
