### ISSUE TITLE
Move sysinfo syscall bypass into the kernel

### ISSUE THREAD

**Issue by davidchisnall** [lsds/sgx-lkl#178]
Currently, musl bypasses LKL for sysinfo.  We should make these into proper syscall bypasses in the kernel layer.

**Comment by jxyang** [comment]
https://github.com/lsds/sgx-lkl-musl/pull/15
https://github.com/lsds/sgx-lkl/pull/362

**Comment by davidchisnall** [comment]
Thanks. Please tag the issues in commit messages so that they are automatically associated.
