### ISSUE TITLE
Move mmap-related syscall bypasses into the kernel

### ISSUE THREAD

**Issue by davidchisnall** [lsds/sgx-lkl#179]
SGX-LKL provides its own implementation of the mmap family of APIs and musl calls these directly instead of via the system call layer.  This can't be done until we've removed all malloc / mmap dependencies from code that runs before LKL starts.

The relevant system calls are:

- [ ]  `mmap`
- [ ]  `munmap`
- [ ]  `mremap`
- [ ]  `msync`
- [ ]  `mprotect`

Currently, `mprotect` calls the host directly from userspace.  This call should be moved into the kernel.

**Comment by davidchisnall** [comment]
@SeanTAllen, please close this if it's done.

**Comment by SeanTAllen** [comment]
I don't believe this is done until #604 is done.

**Comment by SeanTAllen** [comment]
Closed by #710.
