### ISSUE TITLE
Reove futex system call bypass

### ISSUE THREAD

**Issue by davidchisnall** [lsds/sgx-lkl#180]
This depends on all consumers of futex-related APIs that run before userspace init moving to calling the enclave futex implementation directly, rather than via musl.

**Comment by prp** [comment]
@davidchisnall thinking about it, I'm still not entirely clear how the interaction between the LKL futex implementation and the lthread scheduler would work. For example, after a futex_wake how would LKL wake up multiple lthreads?

**Comment by davidchisnall** [comment]
As I understand it, it would call `__switch_to` on these threads.  This would `sem_up` their scheduler semaphore.  They would then wake up in whatever system call made them sleep initially, and return.  On their way out, they would call `lkl_cpu_put`, which would note that there are multiple runnable tasks and wake each one in turn.  Each one of these would go through the same process.  When the LKL scheduler finished running for each of these, it would `longjmp` back to the syscall exit path.  At this point, all of the lthreads are runnable and none are holding LKL's CPU lock, so any one of them is able to make system calls.

**Comment by davidchisnall** [comment]
I have now written a test to verify that this works. The original thread spawns two children that wait on the same futex. These sit in a loop with no system calls (so can’t be context switched by lthreads) reading a global, checking in one if it is odd and in the other if it is even.  If the condition matches, they atomically increment it. When it reaches 100, both exit.

This test passes with the futex bypass removed.  Both threads enter the kernel in blocking futex calls and wait. The kernel context switches away from the idle thread, which unlocks the cpu lock and allows other host threads to make system calls. The initial thread is scheduled and makes the futex wake call. The kernel then marks both of the other threads as runnable. When they are switched to, their scheduler semaphore is triggered and after the syscall returns they can wake up, acquire the cpu lock, return, and give up the cpu lock.  They then run.

With this done, we don’t need any special casing for futexes. The host layer can use lthreads futexes, everything else can use LKL futexes. The futex managed by the kernel for thread exit also works correctly, so a task can join cloned threads with a futex (as musl does).

**Comment by davidchisnall** [comment]
Renaming this bug, as I now believe that the correct path is to use the lthreads futex implementation solely for the LKL host layer and use the Linux futex for everything above the kernel.

**Comment by davidchisnall** [comment]
This was done in #306
