### ISSUE TITLE
Remove gettid syscall bypass

### ISSUE THREAD

**Issue by davidchisnall** [lsds/sgx-lkl#182]
Currently, musl skips the gettid system call and instead queries lthread state.  Once clone is implemented and userspace threads are created as kernel-owned threads that are backed by lthreads, then the kernel will return the correct value for gettid and this can be removed.

**Comment by davidchisnall** [comment]
@vtikoo, can you make sure that you're tracking this with the lthread disentangling work?

**Comment by davidchisnall** [comment]
@vtikoo, didn't you fix this?

**Comment by vtikoo** [comment]
Yup, this is fixed by #403.
