### ISSUE TITLE
the issue: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Zxiaoyu95** [lsds/sgx-lkl#19]
When I run the instance of helloworld in the apps/jvm/helloworld-java, I execute the statement "../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld",and an error is reported each time-----"../../../tools/sgx-lkl-java: line 28: 13161 Segmentation fault       (core dumped)        env  LD_LIBRARY_PATH=${JRE_LIB_PATH} ${SGX_LKL_OPTIONS} ${SGX_LKL_RUN_EXEC} ${DISK_IMAGE} # /opt/j2re-image/bin/java  ${DEFAULT_JRE_ARGS} ${ARGS}",
What's the problem?  I hope you can help me with it. thanks

**Comment by conz27** [comment]
@Zxiaoyu95, could this be related to #17? I've run into this running against Ubuntu 16.04 with 4.10 and 4.15 Linux kernel. The patch that @cpriebe mentions may not have been merged into newer kernel branches. I'd try downgrading to a 4.4.0 kernel ... that worked for me.

**Comment by cpriebe** [comment]
As mentioned by @conz27 this might be related to the kernel bug mentioned in #17. Which kernel are you running?

Do you see any JVM error message? Can you run it with `SGXLKL_VERBOSE=1`, i.e.

```SGXLKL_VERBOSE=1 ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld```

to see if it gets to the point where the JVM is running?

What's your OS/kernel?

**Comment by Zxiaoyu95** [comment]
My current working environment  based on cloud virtual machine with Ubuntu 14.04.5 LTS and Linux 3.13.0-163-generic kernel.And I used  a simulation mode to run it.As for the error message, I just saw the error"Segmentation fault " and I have tried the command line you mention,but it didn't work.
After reading #17, I doubt the crux is my lower version.What do you think? @conz27 @cpriebe

**Comment by Zxiaoyu95** [comment]
Ok thank you ,now the segfault has been resolved,but a new error happens:
The command line: sudo SGXLKL_GETTIME_VDSO=0 ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld
Output:  OpenJDK 64-Bit Server VM warning: Can't detect initial thread stack location - find_vma failed
../../../tools/sgx-lkl-java: line 28: 31412 Illegal instruction     (core dumped) env LD_LIBRARY_PATH=${JRE_LIB_PATH} ${SGX_LKL_OPTIONS} ${SGX_LKL_RUN_EXEC} ${DISK_IMAGE} /opt/j2re-image/bin/java ${DEFAULT_JRE_ARGS} ${ARGS}
Do you know the reason for this error :Illegal instruction (core dumped)? @cpriebe

**Comment by Zxiaoyu95** [comment]
I got success with Linux master 4.8.0-36-generic kernel ，Ubuntu 16.04.2 LTS！Thank you for your help! @cpriebe @conz27

**Comment by cpriebe** [comment]
@Zxiaoyu95 Thanks a lot for the feedback! Good to hear that the original issue is resolved now!

It would be interesting to know which instruction is causing this. If you would like to debug this, the best way would be to do the following:

```
# Build SGX-lKL in debug mode
make clean && make sim DEBUG=true
cd gdb
./setup.sh
cd ../apps/jvm/helloworld-java
LD_LIBRARY_PATH=/opt/j2re-image/lib/amd64/server SGXLKL_HEAP=400M SGXLKL_KEY=../../../build/config/enclave_debug.key ../../../gdb/sgx-lkl-gdb --args ../../../build/sgx-lkl-run ./sgxlkl-java-fs.img /opt/j2re-image/bin/java -Xms2m -Xmx100m -XX:ReservedCodeCacheSize=4000K -XX:CompressedClassSpaceSize=4000K -XX:+UseMembar -cp /app HelloWorld
```

In gdb, you should be able to use:
```set disassemble-next-line on
run
```

It should break when the illegal instruction occurs and you should be able to see which instruction is considered illegal. You can also try `layout asm` if that doesn't work.

Do you see the same issue with the C hello world example?

```cd apps/helloworld
make test-pie
```

To debug this one, use:

```../../gdb/sgx-lkl-gdb --args ../../build/sgx-lkl-run sgxlkl-disk.img app/helloworld-pie```


If there is a way for us to reproduce this (e.g. if this is a public cloud provider and a standard VM), let us know!

**Comment by Zxiaoyu95** [comment]
Tahnk you @cpriebe ,I followed the command line you gave me to build SGX-lKL in debug mode,the lucky code works!

In addition, I would like to ask if the Hadoop program can run in this environment, and every task process can run in SGX environment. Do you have any good Suggestions?

**Comment by Zxiaoyu95** [comment]
When I run the helloworld instance in Hardware mode ,The command line prompts:
Failed open SGX device：
/dev/isgx:No such file or directory
/dev/sgx:No such file or directory
I want to ask what isgx and sgx mean? How can I solve this problem?Thank you very much for your useful answers! @cpriebe

**Comment by Zxiaoyu95** [comment]
When I run the helloworld instance in Hardware mode ,The command line prompts:
Failed open SGX device：
/dev/isgx:No such file or directory
/dev/sgx:No such file or directory
I want to ask what isgx and sgx mean? How can I solve this problem?(I have installed the SGX-master and Intel SGX driver) Thank you very much for your useful answers! @cpriebe

**Comment by cpriebe** [comment]
If it works in debug mode it should also work in regular mode! I am not sure why SGX-LKL in simulation mode would fail to run in a VM. I vaguely remember having seen a similar issue before, but unfortunately I don't remember what caused it. It could be that the JVM was compiled to use certain instructions like SSE4 or AVX instructions that are not supported by the VM you are running on.


Regarding `/dev/isgx` and `/dev/sgx`: One of those devices should be exposed after installing the driver. However, that would only work on a system that actually has SGX support. SGX generally has support for virtualization, but you should make sure that your VM is set up correspondingly. You can use a tool like this one to check if SGX is enabled:

https://github.com/ayeks/SGX-hardware/blob/master/test-sgx.c

**Comment by Zxiaoyu95** [comment]
![image](https://user-images.githubusercontent.com/40795016/51535770-62959f80-1e84-11e9-8c7b-e19d644eb6f4.png)

Thanks for your enthusiastic answer. I think my machine supports SGX because I have done experiments on SGX before. Could you please help me look at the operation result to determine the problem ? 

Thanks

**Comment by Zxiaoyu95** [comment]
At present, we are doing experiments on hadoop and want to run the mapreduce program in your environment. Due to the distributed structure of cloud computing, we do not know how to run each Task in this environment. Do you have any Suggestions?Hope to get your reply, thank you! @cpriebe

**Comment by cpriebe** [comment]
Regarding the `/dev/sgx` and `/dev/isgx` devices: Those aren't related to SGX-LKL. You should see at least one of those, otherwise I would be surprised if you could run other things (e.g. applications built with the SDK) on SGX.

We haven't done any work on running Hadoop with SGX-LKL. SGX-LKL does support JVM applications, so you could certainly give it a try. You can run multiple enclaves that communicate with each other over network just as with a set of nodes of an application that are run natively.

**Comment by cpriebe** [comment]
I'm closing this issue as the original issue has been resolved.
