### ISSUE TITLE
Default for number of ethreads should not exceed num_tcs

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#210]
https://github.com/lsds/sgx-lkl/blob/ce88f974da24683bdf2903bf3c165724954a3dcc/src/main-oe/sgxlkl_run_oe.c#L1774-L1778

This will lead to `OE_OUT_OF_THREADS` if `SGXLKL_ETHREADS` hasn't been specified and `num_tcs` < `nproc` where `num_tcs` is currently set to 8 in [config/params.conf](https://github.com/lsds/sgx-lkl/blob/oe_port/config/params.conf).

**Comment by prp** [comment]
@wintersteiger since we're choosing the number of TCS dynamically, this is a non-issue now, right? Can this be closed?

**Comment by wintersteiger** [comment]
I think so, yes. I'm not sure what the SGX limit is and what happens if someone tries to run with more than that.

**Comment by prp** [comment]
OE has a hard limit of 32 TCS (see [here](https://github.com/openenclave/openenclave/blob/0199244b6b7340d2cfb4af02990542f514e72cdc/include/openenclave/bits/sgx/sgxproperties.h#L29)). I'm closing this issue, as increasing the default OE limit is not an SGX-LKL issue.
