### ISSUE TITLE
Support relative path for app executable

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#212]
If a Dockerfile has `ENTRYPOINT ["python3"]` then this will work if the base image (some Ubuntu) includes `/usr/bin` in the `PATH` environment variable (I'm assuming the Docker daemon replicates the usual shell search logic). Similary, if the Dockerfile has `WORKDIR /foo` and `ENTRYPOINT ./myapp` then it will run `/foo/myapp`.

SGX-LKL takes neither the working directory nor `PATH` into account and will only accept absolute executable paths. This means automatic conversion with `sgx-lkl-disk` + `sgx-lkl-cfg` will produce an invalid app config. Even if `sgx-lkl-cfg` is not used and instead the app config is hand-crafted it may still be confusing/surprising.

**Comment by davidchisnall** [comment]
We probably need this for a lift and shift model, but I wonder if it’s better to build it into the tooling. I am a bit nervous of the idea that the binary to launch is not always fully explicit in the attested host configuration. I wonder if we could expand the path to a fully qualified path when building the wrapper?

**Comment by letmaik** [comment]
I agree, I had the same concern. I'll have a look at how tooling can resolve the path. What I know is that the resolved path is not part of any of the Docker container metadata (which we use in `sgx-lkl-cfg` to generate app config files). I guess we can peek into the filesystem ourselves though and resolve it ourselves.

**Comment by davidchisnall** [comment]
Assuming that we have (a copy of) the unencrypted filesystem at that point, it sounds like the best solution.  It's a bit more complex if we want to use the same confidential container image with multiple configurations, though it's a slightly strange idea to have people able to run arbitrary commands in a container without their having access to the default configuration.  We might want to add an attested flag to say 'resolve the command using $PATH' and have it off by default?

**Comment by letmaik** [comment]
I'll close this for now as #228 provides a reasonable tooling work-around for this.
