### ISSUE TITLE
Timeouts in LTP tests not marked as such

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#217]
Example: https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=219&view=ms.vss-test-web.build-test-results-tab&runId=1886&resultId=100091&paneView=attachments

This should print something to stderr if the test timed out. Currently no error is visible in the log in this case.

@hukoyu Could you have a look at that? The exit code has to be checked and if it is 124 then it timed out. Please see the equivalent logic in run_test.sh.

**Comment by hukoyu** [comment]
Sure @letmaik I will fix that in LTP test runner. I will submit a PR for that.

**Comment by hukoyu** [comment]
@letmaik submitted PR https://github.com/lsds/sgx-lkl/pull/220 for this issue.
