### ISSUE TITLE
Can't run Hello world apps

### ISSUE THREAD

**Issue by kanakraju73** [lsds/sgx-lkl#22]
My PC stats:
Dell precision 3630 Tower
Memory: 31,1 GiB
CPU: Intel:registered: Core:tm: i7-8700 CPU @ 3.20GHz × 12
OS: Ubuntu 18.04.1 LTS 64-bit
Kernel: 4.15.0-44-generic

Make finished without errors
But when i try to run the jvm hello world I got the following error

kanak@wp-04:~/sgx-lkl/apps/jvm/helloworld-java$ sudo SGXLKL_VERBOSE=1 ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld
[ SGX-LKL ] No tap device specified, networking will not be available.
Error while initializing enclave, error code: 1073741825

Then i tried to provide tap device using the following but the issue still remain.

@wp-04:~/sgx-lkl/apps/jvm/helloworld-java$ sudo SGXLKL_TAP=sgxlkl_tap0 SGXLKL_VERBOSE=1 ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld
Error while initializing enclave, error code: 1073741825

I'm using the sdk and driver version 2.0 on ubuntu 18.04
Help me resolve the problem

**Comment by kanakraju73** [comment]
Make finished without errors 
But when i try to run the jvm hello world  I got the following error

kanak@wp-04:~/sgx-lkl/apps/jvm/helloworld-java$ sudo SGXLKL_VERBOSE=1 ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld
[    SGX-LKL   ] No tap device specified, networking will not be available.
Error while initializing enclave, error code: 1073741825

Then i tried to provide tap device using the following but the issue still remain.

@wp-04:~/sgx-lkl/apps/jvm/helloworld-java$ sudo SGXLKL_TAP=sgxlkl_tap0 SGXLKL_VERBOSE=1 ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld
Error while initializing enclave, error code: 1073741825

I'm using the sdk and driver version 2.0 on ubuntu 18.04
Help me resolve the problem

**Comment by cpriebe** [comment]
Hi @kanakraju73 

Thanks for reporting this. The TAP message is just a warning and can be ignored in this case. The enclave initialization error should obviously not happen though. Have you verified, e.g. with the Intel SDK that SGX is set up correctly?

**Comment by cpriebe** [comment]
Actually, there is no official 2.0 driver for Ubuntu 18.04, so you probably want to try either 2.3 or 2.4 (see https://01.org/intel-software-guard-extensions/downloads). I am aware we currently say we have tested SGX-LKL with versions 1.9 and 2.0 and Ubuntu 16.04. That information is a bit outdated though. I'll update that.

**Comment by kanakraju73** [comment]
Hi @cpriebe 

Thanks for the reply. I've updated my sgx drivers and sdk to 2.4 

SDK Sample Code works fine with the current setup 

SampleEnclave:

kanaka@wp-04:/opt/intel/sgxsdk/sgxsdk/SampleCode/SampleEnclave$ ./app 
Checksum(0x0x7ffcafb876a0, 100) = 0xfffd4143
Info: executing thread synchronization, please wait...  
Info: SampleEnclave successfully returned.
Enter a character before exit ...


Local Attestation:
kanaka@wp-04:/opt/intel/sgxsdk/sgxsdk/SampleCode/LocalAttestation$ ./app 

Available Enclaves
Enclave1 - EnclaveID 2
Enclave2 - EnclaveID 3
Enclave3 - EnclaveID 4

Secure Channel Establishment between Source (E1) and Destination (E2) Enclaves successful !!!

Enclave to Enclave Call between Source (E1) and Destination (E2) Enclaves successful !!!

Message Exchange between Source (E1) and Destination (E2) Enclaves successful !!!

Secure Channel Establishment between Source (E1) and Destination (E3) Enclaves successful !!!

Enclave to Enclave Call between Source (E1) and Destination (E3) Enclaves successful !!!

Message Exchange between Source (E1) and Destination (E3) Enclaves successful !!!

Secure Channel Establishment between Source (E2) and Destination (E3) Enclaves successful !!!

Enclave to Enclave Call between Source (E2) and Destination (E3) Enclaves successful !!!

Message Exchange between Source (E2) and Destination (E3) Enclaves successful !!!

Secure Channel Establishment between Source (E3) and Destination (E1) Enclaves successful !!!

Enclave to Enclave Call between Source (E3) and Destination (E1) Enclaves successful !!!

Message Exchange between Source (E3) and Destination (E1) Enclaves successful !!!

Close Session between Source (E1) and Destination (E2) Enclaves successful !!!

Close Session between Source (E1) and Destination (E3) Enclaves successful !!!

Close Session between Source (E2) and Destination (E3) Enclaves successful !!!

Close Session between Source (E3) and Destination (E1) Enclaves successful !!!

Hit a key....


I've rebuilt sgx-lkl still the issue remain,

kanaka@wp-04:~/sgx-lkl/apps/jvm/helloworld-java$ ../../../tools/sgx-lkl-java ./sgxlkl-java-fs.img HelloWorld
Error while initializing enclave, error code: 1073741825


Btw my kernel version is 4.15.0-45
kanaka@wp-04:~/sgx-lkl/apps/jvm/helloworld-java$ uname -r
4.15.0-45-generic

I've looked into this https://github.com/lsds/sgx-lkl/issues/19#issuecomment-455942517 and tried downgrading my kernel to 4.8.0-040800-generic and got success

I'd like to know what was the latest version you're able to run the sample apps.
Thanks in advance 

Regards,
Kanaka

**Comment by cpriebe** [comment]
Hi @kanakraju73, apologies for the delay!

I'm still unsure what is going wrong. I have tested the following configurations which all work. I have tried to run the HelloWorld example, redis (see `apps/miniroot`), and the JVM HelloWorld example. The JVM example still fails with a JVM error (not an enclave initialization error) due to the kernel bug described in #17. This issue has been fixed in the bionic-proposed kernel which should be released in the next few weeks. Anyway, this is not the problem that you are seeing.

1.
Intel(R) Core(TM) i5-8250U v8 CPU @ 1.60GHz
Ubuntu 18.04.01 LTS
4.15.0-45-generic #48
Driver: 2.4

2.
Intel(R) Xeon(R) CPU E3-1280 v6 @ 3.90GHz
Ubuntu 18.04.02 LTS
4.15.0-45-generic #48
Driver: 2.3

3.
Intel(R) Xeon(R) CPU E3-1280 v6 @ 3.90GHz
Ubuntu 18.04.02 LTS
4.15.0-45-generic #48
Driver: 2.4

I assume `dmesg` does not contain any useful information when the initialization is failing?

**Comment by cpriebe** [comment]
Two more questions:
1) Did you also update libenclave-common to 2.4?
2) Which of `/dev/sgx` and `/dev/isgx` are available on your system?

**Comment by kanakraju73** [comment]
Hi @cpriebe 

Firstly thanks for the reply.
- I've updated my kernel to 4.17.17 and able to run all the sample apps.

And coming to your questions 

> 1. Did you also update libenclave-common to 2.4?

Yes

> 2. Which of /dev/sgx and /dev/isgx are available on your system?

I can only see /dev/isgx and you can see that below 

kanaka@wp-04:\~/clones/python-sgx/tests$ ls /dev/isgx >/dev/null 2>1  && echo "ISGX" || echo "NO ISGX"
ISGX
kanaka@wp-04:~/clones/python-sgx/tests$ ls /dev/sgx >/dev/null 2>1  && echo "SGX" || echo "NO SGX"
NO SGX

Now that my original issue is solved i'm closing this issue.
