### ISSUE TITLE
How to deploy secure docker container with SGX-LKL?

### ISSUE THREAD

**Issue by phyomaythet** [lsds/sgx-lkl#23]
Is it possible to deploy existing docker container to run with SGX-LKL support? e.g. I already have a working docker container without SGX support and I would like to integrate that docker container and SGX-LKL in simulation mode. Is it possible to integrate?Thanks for your suggestion.

**Comment by cpriebe** [comment]
Do you want to deploy SGX-LKL itself as part of a Docker container? If so you might want to have a lock at the [Dockerfile](https://github.com/lsds/sgx-lkl/blob/master/Dockerfile) and the corresponding [sgx-lkl-docker.sh](https://github.com/lsds/sgx-lkl/blob/master/sgx-lkl-docker.sh) script in the main repository. See https://github.com/lsds/sgx-lkl#building-sgx-lkl-using-docker.

In case you have a Dockerfile or a Docker image that contains an application you want to deploy the easiest way to run it with SGX-LKL is to create a corresponding disk image with the `sgx-lkl-disk` tool. Keep in mind that applications need to be linked against musl. The easiest way to achieve this is to use an Alpine-based Docker image. The `--docker` argument also supports Docker image IDs as well as images that are available on the Docker Hub registry. See https://github.com/lsds/sgx-lkl#creating-sgx-lkl-disk-images-with-sgx-lkl-disk.

Let us know if things are unclear!

**Comment by phyomaythet** [comment]
Thank you very much for your information. I will try again.
