### ISSUE TITLE
Remove --size requirement from sgx-lkl-disk when used with --docker flag

### ISSUE THREAD

**Issue by conz27** [lsds/sgx-lkl#24]
Docker has built-in tools that can give the exact image size without having to make the user explicitly specify it.

`docker image inspect <image_name> --format='{{ .Size }}'` returns the image size in bytes.

Ideally, a user should only have to do the following:
`./sgx-lkl-disk --create --docker=<image_name|Dockerfile>`

In the case "Dockerfile" is supplied, sgx-lkl-disk may have to define a default image name and use that name to run the image inspect command above.

On a side note,  action based arguments like "create" should probably not be flags. In my mind, this looks better:
`./sgx-lkl-disk create --docker=\<image\>`

**Comment by cpriebe** [comment]
Hi @conz27,

Thanks a lot! I wasn't aware I could get the size of the image that way. Unfortunately it seems like this does not exactly reflect the size after creating a corresponding container and exporting it. See for example:

```
$ docker pull alpine:3.9
$ docker image inspect alpine:3.9 --format='{{ .Size }}'
5529164
$ docker create --name myalpine alpine:3.9
$ docker export myalpine > myalpine.tar
$ mkdir myalpine
$ tar xf myalpine.tar -C myalpine
$ du -s -B1 myalpine
6103040	myalpine
```
We could get the expected size from `tar` but I believe that still wouldn't cover the additional overhead from file / file system metadata that needs to be taken into account. Also, `--docker` can be used together with `--copy` which would have to be included in the calculation. Obviously all of this would only work for read-only images. I will look into this but I believe this would require a bit more work. Maybe a more robust approach would be to choose a conservative size when creating the disk image and then resizing/shrinking it afterwards.


I also agree with you on the action arguments. I remember starting to do this in the past and then something else got in the way. Anyway, I have changed this now in ef44815.

**Comment by conz27** [comment]
@cpriebe, good stuff with the action arguments change!
