### ISSUE TITLE
CI: stdout/stderr missing for passing tests

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#242]
Only failing tests have their stdout/stderr stored as part of the test results. There are cases where I'd still want to have it available for comparison with a failing test and for sanity checking.

@hukoyu Could you have a look at this?

**Comment by hukoyu** [comment]
@letmaik actually all logs for passed and failed tests are available in the zip file for test summary. The logs are in junit xml for all tests regardless passed or failed but AzureDevOps doesn't display stderr and stdout logs for passed tests, it only shows for failed tests. I investigated a bit but couldn't find a way how to display it on AzureDevOps. But as workaround, you can download the zip file and unzip and check logs for any passed/failed test. Here is a sample screenshot for link to zip file:
![image](https://user-images.githubusercontent.com/61761684/81879694-56819580-9540-11ea-9660-15b6e0262f9e.png)

**Comment by letmaik** [comment]
I see, didn't know it was a DevOps issue. I wonder if we should report that, seems like a bug to me.

**Comment by letmaik** [comment]
I found https://developercommunity.visualstudio.com/content/problem/631082/printing-the-console-output-in-the-azure-devops-te.html:
> The product currently does not support printing console logs for passing tests and we do not currently have plans to support this in the near future. 

How sad, but ok. The work-around you suggested does work.
