### ISSUE TITLE
Document how to pass application environment variables to sgx-lkl-run

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#26]
I couldn't find any mention of how to pass environment variables to the executable within the enclave file system. Is this supported at all? If not, are there work-arounds?

**Comment by cpriebe** [comment]
Right now you should be able to just specify them alongside the `SGXLKL_*` configuration variables as you would do for any application.

In the future you'll be able to explicitly specify the set of application-specific environment variables but that's still work in progress.
