### ISSUE TITLE
No network interface, cannot connect to host (JVM)

### ISSUE THREAD

**Issue by melbek** [lsds/sgx-lkl#27]
Hi everyone,

Background:
I am building an system consisting of one server sitting on the host and one client loaded into sgx-lkl. The connection is done via TCP sockets, so I need a connection from sgx-lkl to the host machine.
I followed the tutorial and got the JVM HelloWorld to run, adapted everything to load my jar application without networking at first and everything worked (after adjusting the sizes).
I also followed the steps in "Networking support", but still cannot reach the server from the sgx-lkl client. I iterated over the network interfaces in Java but got only the 127.0.0.1 one, so I think sgx-lkl is not using the IP 10.0.1.1.
I am using a fresh Ubuntu 18.04.01 server installation.
Can you please point me into some direction? I know its not much information, I am not good in networking and linux so I will provide everything you ask for.

Thank you in advance!

**Comment by cpriebe** [comment]
Did you specify `SGXLKL_TAP=sgxlkl_tap0` (adjust the name of the interface if necessary)? If you do so, a `eth0` interface (with IP `10.0.1.1` by default) should be accessible from within the enclave.

**Comment by melbek** [comment]
Ah no! Thank you cpriebe! 
I thought that's an optional step only after changing the IP, my bad.
