### ISSUE TITLE
[Tests] access02 test spuriously passes

### ISSUE THREAD

**Issue by davidchisnall** [lsds/sgx-lkl#277]
This test runs the `system` libc function:

https://github.com/linux-test-project/ltp/blob/5004658ae0cd0973fce8b2bb6e68d898812b254e/testcases/kernel/syscalls/access/access02.c#L130

This is implemented with `posix_spawn` in musl, which in turn, is implemented with `clone`.  In the `oe_port` branch currently, `clone` is not implemented and so the `system` call fails but the test passes.  Once the `clone` system call actually works, this test begins failing because the rest of musl has not yet been updated to support a working `clone` call.

This test should not be passing while attempting to execute unimplemented functionality

**Comment by hukoyu** [comment]
@ashokchandran can you investigate this?

**Comment by hukoyu** [comment]
This test is disabled for now

**Comment by SeanTAllen** [comment]
This has been fixed, the test was turned off.
