### ISSUE TITLE
How the application (running on the sgx-lkl) interaction with the local operating system

### ISSUE THREAD

**Issue by Zxiaoyu95** [lsds/sgx-lkl#29]
Recently,i meet a problem when i run application on the sgx-lkl, and i have some confusion about sgx-lkl.I hope to get your reply.Thank you!
1) Is the Disk image named sgxlkl-java-fs.img  running in the sgx environment? How to understand /sgx-lkl-run to execute it?
2) When i start a jvm for an application process,the classpath I need a local temporary file,so i  am trying to link a local file with the file in the Disk image,but when i run the process on the sgx-lkl, a error shows that file not exist.so i want to know how the application (running on the sgx-lkl) interaction with the local operating system.

**Comment by cpriebe** [comment]
Hi @Zxiaoyu95 ,

Yes, the disk image you provide to sgx-lkl-run is exposed inside enclave as root file system. Once inside the enclave, you have no access to any file on the host file system (on purpose). You will have to modify the disk image if you want to expose additional files inside the enclave, or create them at runtime.

If you are using the helloworld-java Makefile as a basis, you can add additional files to the disk image by modifying the `$(ROOT_FS)` target and add something like:

`cp /host/file/sytstem/myfile $(MOUNTPOINT)/`

In this example `myfile` would be accessible inside the enclave at `/myfile`.

**Comment by Zxiaoyu95** [comment]
Thank you @cpriebe for your reply.
Now,because my application takes up too much space,so i just use sgx-lkl to start a JVM for an application process,the rest is executed outside of sgx-lkl ,and main file on the host file system is temporary,so i link the file with image file like command:
ln -s   $(MOUNTPOINT)/   /host/file/sytstem/myfile   
the file is linked successfully,but when i run the process on the sgx-lkl,the error shows the file does not exist ,so i wonder if it was a sgx-lkl permission issue that caused this error.

**Comment by Zxiaoyu95** [comment]
Since I do not have a deep understanding of sgx-lkl, so is there any paper or document about it? I want to use this wonderful project to develop my own application, so i want to know more about it .
Thank you!

**Comment by cpriebe** [comment]
As I said you will not be able to access files from your host file system from within the enclave. The only option you have is to copy the file to the disk itself. Or modify SGX-LKL. It would theoretically be possible to extend it to allow you to access the host file system but that also increases the attack surface which we don't really want to do.

Regarding your second point. We are working on a write up right now but it is not available yet. That said we definitely should also improve the README as well as the information available in the wiki. We'll work on that soon.

**Comment by Zxiaoyu95** [comment]
ok ,looking forward to seeing more information about sgx-lkl in the future. Thank you @cpriebe  for your reply!

**Comment by cpriebe** [comment]
I'll close this for now as the original issue has been addressed.

**Comment by kanakraju73** [comment]
Any update on this?
