### ISSUE TITLE
SGX-LKL tls area seems very small. Can cause OE to segfault on reads.

### ISSUE THREAD

**Issue by jhand2** [lsds/sgx-lkl#291]
OE checks to see if SGX-LKL has changed %fs by checking for a magic number at %fs:168. Space before that is left for SGX-LKL (or any other application that cares about threading) to do whatever it needs.

When SGX-LKL changes %fs, it allocates a TLS area and then sets fs to that area. The issue is that the tls area is only 80 bytes (determined by libc.tls_size). If the tls area is allocated near the end of the heap, a read at %fs:168 will segfault.

80 is larger than SGX-LKL's thread control block, but fairly small in terms of being used for usermode tls. It is unclear to me why this value was chosen or how SGX-LKL makes use of it's TLS area.

I am wondering if it is possible for this area to be larger so that the OE read of the magic number is  at least accessible memory. This would mean adding padding to SGX-LKL's thread control block `lthread_tcb_base`. Let me know if this seems reasonable or if anyone has any concerns about doing this.

**Comment by SeanTAllen** [comment]
@jhand2 does this happen in both SW and HW mode or only HW?

**Comment by davidchisnall** [comment]
I don't think we can guarantee this in the general case.  Linux programs can set %fs clone.  libc does this in pthread creation and the size of this depends on the .tdata and .tbss segments in the binary.  Other user code in non-C languages may opt out of TLS entirely for some threads and set %fs to 0 or something just big enough for the stack canary if it wants to call C code.  Even if we guarantee this for %fs values initialised by us, we are just changing from failing all of the time to failing in the cases that are hardest to debug.

Would it be possible to have an explicitly opt-in API for OE consumers that wanted to take control over either %fs or %gs (and require that they not take control over both)?

**Comment by jhand2** [comment]
@davidchisnall that would probably be fine. In the short term (to make sure this is actually what's causing the problem) I can just check if %fs:0 == %gs:0. If not OE would just use %gs.

That's also currently how we decide whether to save/restore fs on ocall.

Making a new API is a little more complicated since we currently don't have a concept of exposing an API which only applies to one architecture (although we're working on what that should look like going forward).

**Comment by jhand2** [comment]
This should be fixed here: https://github.com/openenclave/openenclave/commit/8fcf9b79d3855f9b7ed0bd42e510282813413d4e

Waiting on @wintersteiger to confirm everything looks good from his end. I'll open an issue in OE to track a longer term change to allow applications to reserve use of fs or gs

**Comment by wintersteiger** [comment]
Confirmed! Everything's working on my end too. Thanks for the quick fix!

**Comment by SeanTAllen** [comment]
Is this change picked up by CI immediately or does something have to be updated?

**Comment by wintersteiger** [comment]
It's in OE `feature/sgx-lkl-support`, but I'm not sure whether all pipelines are set up to use that branch.

**Comment by davidchisnall** [comment]
@jhand2, unless I'm misreading the code (given how badly I slept last night, around a 70% probability), the logic that does `if (gs == fs) fs else gs` is equivalent to `gs`.  If the user modifies `gs` but not `fs`, you'll still return `gs` and get the wrong value.

**Comment by wintersteiger** [comment]
Good point @davidchisnall , I agree, it's just `return gs`. (I also slept quite badly though :-))

**Comment by jhand2** [comment]
@davidchisnall Yes, I made this change specifically to fix an OE bug based on the way SGX-LKL works today (this commit is not in master) to unblock folks quickly. A longer term solution is probably necessary but I don't have the time to invest in that right now.

As I understood it, SGX-LKL has no need to make use of GS. Is that still the case?

**Comment by davidchisnall** [comment]
SGX-LKL does not need to control %gs, but does need a place to store a (pointer to a) per-ethread structure. In the OE-managed %gs section would be ideal. For now, we can use an unused space in this structure, but ideally we’d like to have an API for accessing this (which, eventually, can be portable to other enclave technologies and architectures).

**Comment by jhand2** [comment]
@davidchisnall the first 168 bytes (other than the self pointer and stack pointer) are unused by OE (by design). Feel free to use any of that space.

As for an API/additional asks, would you be able to open issues on the OE github repo? I can't really make unilateral decisions about new APIs, so it would be best to get feedback from others as well.

**Comment by davidchisnall** [comment]
Thanks.  If the first 168 bytes is part of the ABI, can that be documented somewhere as a guarantee from OE?

**Comment by jhand2** [comment]
It is a specific change made to support SGX-LKL. While it is in master, I'm not sure if we want to commit to that as part of the ABI. I think your proposal for an API is probably a better long-term solution.

**Comment by SeanTAllen** [comment]
As part of triaging, it was believed this was fixed and no longer an issue. If that is incorrect, please reopen.
