### ISSUE TITLE
sgxlkl_enclave_init kernel panic

### ISSUE THREAD

**Issue by ashokchandran** [lsds/sgx-lkl#301]
Saw some tests randomly failing in the pipeline while creating an enclave with signature of a kernel panic in sgxlkl_enclave_init.  Individually they pass. I think it is related to multiple pipeline tests initiated in parallel as PRs are being submitted in parallel. 
pipleline log: 
kernel-syscalls-pipe2-pipe2_01-(nonrelease)-(run-hw)-(8-ethreads)
'kernel-syscalls-pipe2-pipe2_01-(nonrelease)-(run-hw)-(8-ethreads)' failed. Failure Count = 1, Pass Count = 0 'make run-hw-single test=/ltp/testcases/kernel/syscalls/pipe2/pipe2_01' can be used to test this individually failing ltp test
[   SGX-LKL  ] SGX-LKL (OE) Git version b0678cd-dirty LKL version 5.3.0 [NON-RELEASE build (-O3)] [HARDWARE DEBUG]
[   SGX-LKL  ] Warning: SGXLKL_TRACE_SIGNAL ignored in non-debug mode.
[   SGX-LKL  ] nproc=4 ETHREADS=8 CMDLINE="mem=512m"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='sgxlkl-miniroot-fs.img', mnt='/', [RW   ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-nonrelease/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
**[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] FAIL: Kernel panic! Aborting...**
[   SGX-LKL  ] ethread (5: 19) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (id=5 result=19 (OE_ENCLAVE_ABORTING))

kernel-syscalls-fcntl-fcntl02-(debug)-(run-hw)-(8-ethreads)
'kernel-syscalls-fcntl-fcntl02-(debug)-(run-hw)-(8-ethreads)' failed. Failure Count = 1, Pass Count = 0 'make run-hw-single test=/ltp/testcases/kernel/syscalls/fcntl/fcntl02' can be used to test this individually failing ltp test.

[   SGX-LKL  ] SGX-LKL (OE) Git version c78da34-dirty LKL version 5.3.0 [DEBUG build (-O0)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=4 ETHREADS=8 CMDLINE="mem=512m"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='sgxlkl-miniroot-fs.img', mnt='/', [RW   ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
**[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] FAIL: Kernel panic! Aborting...**
[   SGX-LKL  ] ethread (4: 19) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (id=4 result=19 (OE_ENCLAVE_ABORTING))

kernel-syscalls-fcntl-fcntl34-(debug)-(run-hw)-(8-ethreads)
'kernel-syscalls-fcntl-fcntl34-(debug)-(run-hw)-(8-ethreads)' failed. Failure Count = 1, Pass Count = 0 'make run-hw-single test=/ltp/testcases/kernel/syscalls/fcntl/fcntl34' can be used to test this individually failing ltp test.
[   SGX-LKL  ] SGX-LKL (OE) Git version c78da34-dirty LKL version 5.3.0 [DEBUG build (-O0)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=4 ETHREADS=8 CMDLINE="mem=512m"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='sgxlkl-miniroot-fs.img', mnt='/', [RW   ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] wg0 has public key 7RKJUzoVYRbWANYdBFm1XiMs4EV/8ucn8RqrSYVelTs=
TIMED OUT after 60 secs. TEST_FAILED

**Comment by hukoyu** [comment]
@ashokchandran  in the description of this issue last sample you added is not Kernel Panic but tiemout issue. Is it really same bug? As far as I know, one pipeline agent runs on each VM, so there shouldn't be multiple tests running on the same VM at the same time. And tests run sequentially. Can you explain more what you mean by 

" I think it is related to multiple pipeline tests initiated in parallel as PRs are being submitted in parallel."

**Comment by ashokchandran** [comment]
It was my initial thought. As you said if they are on different VMs then it is not a factor.  Both are failing in sgxlkl_enclave_init that is enclave initialization with similar signature. So i have used same issue to track them.
