### ISSUE TITLE
Compile flag variables are confusing (SGXLKL_CFLAGS vs SGXLKL_CFLAGS_EXTRA etc.)

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#313]
The SGXLKL_CFLAGS/SGXLKL_CFLAGS_EXTRA makefile variables are quite confusing as it's not clear from the name which one is used where. It seems like SGXLKL_CFLAGS is used *only* for the *.c files in tools/ and SGXLKL_CFLAGS_EXTRA for all other SGX-LKL code (host and enclave), but excluding third-party dependencies (for which there is THIRD_PARTY_CFLAGS).

I suggest replacing the above SGXLKL_* variables with new `SGXLKL_HOST_CFLAGS` and `SGXLKL_ENCLAVE_CFLAGS` variables.

Similarly, there should be `THIRD_PARTY_HOST_CFLAGS` and `THIRD_PARTY_ENCLAVE_FLAGS`.

@prp Does this make sense to you? Am I missing something?

**Comment by prp** [comment]
@letmaik won't this problem go away once https://github.com/lsds/sgx-lkl/issues/326 is done?

**Comment by letmaik** [comment]
I hope so :) You can very easily do nasty stuff in CMake as well though.

**Comment by letmaik** [comment]
Closing this, I'm trusting @davidchisnall to do the right thing.
