### ISSUE TITLE
Should host code be compiled with glibc?

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#315]
The host code is currently built with musl from `host-musl/`. I couldn't find anything in the docs on whether this is strictly required or just a historic artifact. If the latter, wouldn't it be simpler to just use the default standard library from the system (glibc) and remove host-musl/?

@prp @davidchisnall

**Comment by davidchisnall** [comment]
Host code shouldn't need to be compiled with musl.  The host-musl should be for things that are compiled to run in the enclave (they are built against host-musl, but actually end up linked against sgx-lkl-musl).  

Unfortunately (I think), the current build system builds some libraries once and uses them both inside and outside the enclave.  In the wip-cmake branch I've started trying to disentangle this.  I'll return to it once we are a bit further along the relayering.

**Comment by prp** [comment]
@letmaik are you sure about this? For example, [this](https://github.com/lsds/sgx-lkl/blob/e842e1bbf2cdb5211de4b0723fd917bf97709990/src/Makefile#L102) suggests that we use `gcc` to build the launcher.

**Comment by letmaik** [comment]
Hm, you may be right. It's quite hard to understand what things are in the makefiles. It seems the host code is also using a special linker script tools/sgx-lkl.ld. Why is that necessary?

**Comment by prp** [comment]
I believe that special linker script isn't needed anymore. All of this should simplify after https://github.com/lsds/sgx-lkl/issues/326.

**Comment by jxyang** [comment]
I believe host musl is built with gcc, but the outcome is musl-gcc that is used to build all binaries eventually linked into libsgxlkl.so.

**Comment by prp** [comment]
> I believe host musl is built with gcc, but the outcome is musl-gcc that is used to build all binaries eventually linked into libsgxlkl.so.

Right, but that is the enclave library. @letmaik's question was specifically about the host-side code.

**Comment by davidchisnall** [comment]
FYI: In the wip-cmake branch, I am compiling the host code without a special linker script and linking against glibc.  This produces a working host binary.  I have not made this a PR yet because it can't build all of the in-enclave code.  The build system will need to change after the relayering work, so I have not yet prioritised it, but I'd be happy if anyone else wanted to work on it...

**Comment by prp** [comment]
I think that it makes sense to finish the relayering first and then update the build system (once).

**Comment by letmaik** [comment]
OK, I'm closing this, since host code apparently is already built against glibc.
