### ISSUE TITLE
FAIL: Bug: next_delay_ns already set for timer with SGXLKL_ETHREADS=1

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#334]
With SGXLKL_ETHREADS=1 below 4 tests fails in nightly sgx-lkl pipeline:

[[ SGX-LKL ]] FAIL: Bug: next_delay_ns already set for timer
[ SGX-LKL ] init (0: 19 exit=0) [ SGX-LKL ] FAIL: sgxlkl_ethread_init() failed (ethread_id=0 result=19 (OE_ENCLAVE_ABORTING))

**These tests fail with same failure**:
basic-sleep-(debug)-(run-hw)-(1-ethreads)
basic-nonroot_halt_test-(debug)-(run-hw)-(1-ethreads)
java-thread-(debug)-(run-hw)-(1-ethreads) 
dotnet-(debug)-(run-hw)-(1-ethreads)

**Comment by hukoyu** [comment]
@prp repro steps:
1. Build sgx-lkl
2. Go under /sgx-lkl/tests/basic/sleep
3. Modify Makefile and add SGXLKL_ETHREADS=1 to the beginning of SGXLKL_ENV
4. Run "make run-hw"
5. This doesn't fail every time. But if you run 5-10 times you will hit the bug.  

Here is a sample log from local run when failed:
[[  SGX-LKL ]] lkl_start_init(): lkl_start_kernel() finished
[[  SGX-LKL ]] lkl_start_init(): creating LKL termination thread
[[  SGX-LKL ]] create_lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_start_init(): calling lkl_mount_virtial()
[[  SGX-LKL ]] lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_termination_thread(): Performed LKL syscall to get host task allocated (pid=36)
[[  SGX-LKL ]] lkl_start_init(): calling init_random()
[[  SGX-LKL ]] init_random(): Adding entropy to entropy pool
[    0.096381] random: crng init done
[[  SGX-LKL ]] init_enclave_clock(): Setting enclave realtime clock
[[  SGX-LKL ]] wg0 has public key foHEDdgtbg7TJoPDsoONHRov25XpLK9aqUAEzzvCbAM=
[    0.098646] virtio_blk virtio1: [vda] 10240 512-byte logical blocks (5.24 MB/5.00 MiB)
[[  SGX-LKL ]] FAIL: Bug: next_delay_ns already set for timer
2020-05-28T18:12:54.000000Z [(H)ERROR] tid(0x7f9c2076e700) | :OE_ENCLAVE_ABORTING [../host/calls.c:oe_call_enclave_function_by_table_id:91]
[   SGX-LKL  ] init (0: 19 exit=0) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (ethread_id=0 result=19 (OE_ENCLAVE_ABORTING))
Makefile:29: recipe for target 'run-hw' failed
make: *** [run-hw] Error 1

**Comment by hukoyu** [comment]
cc @davidchisnall @prp @jxyang 
Investigated the failures of nightly sgx-lkl pipeline
https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=491&view=results
There are more tests failing due to this issue:
- basic-exit-(debug)-(run-hw)-(1-ethreads)
- basic-exit_status-(debug)-(run-hw)-(1-ethreads)
- basic-global_vars_test-(debug)-(run-hw)-(1-ethreads)
- basic-helloworld-(debug)-(run-hw)-(1-ethreads)
- basic-abort-(debug)-(run-hw)-(1-ethreads)
- basic-nonroot_halt_test-(debug)-(run-hw)-(1-ethreads)
- basic-signal-(debug)-(run-hw)-(1-ethreads)
- basic-stat-(debug)-(run-hw)-(1-ethreads)
- languages-java-thread-(debug)-(run-hw)-(1-ethreads)
- basic-fsgsbase_unset-(debug)-(run-hw)-(1-ethreads)

std-err:
[[  SGX-LKL ]] FAIL: Bug: next_delay_ns already set for timer
[   SGX-LKL  ] init (0: 19 exit=0) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (ethread_id=0 result=19 (OE_ENCLAVE_ABORTING))

std-out:
[[  SGX-LKL ]] init_enclave_clock(): Setting enclave realtime clock
[    0.087393] virtio_blk virtio1: [vda] 10240 512-byte logical blocks (5.24 MB/5.00 MiB)
2020-05-28T00:19:43.000000Z [(H)ERROR] tid(0x7f24b155a700) | :OE_ENCLAVE_ABORTING [../host/calls.c:oe_call_enclave_function_by_table_id:91]
TEST FAILED: raise (HW mode)

**Comment by SeanTAllen** [comment]
I thought this might be related to something I've been looking at so I took a look. I can't reproduce.

Do you have the kernel module installed? That's the only immediate difference I could think of that might be it for local reproduction. I ran the sleep test in a loop in bash for about 30 minutes without issue.

I'm on e842e1bbf2cdb5211de4b0723fd917bf97709990

`SGXLKL_ETHREADS=1 SGXLKL_VERBOSE=1 SGXLKL_KERNEL_VERBOSE=1 /home/sean/code/lsds/sgx-lkl-2020-05-28/build/sgx-lkl-run-oe --hw-debug sgx-lkl-rootfs.img sleep-test`

**Comment by hukoyu** [comment]
@SeanTAllen on my ACC VM, this is how I am building and running tests. Let me know if I am doing something wrong:

git clone git@github.com:lsds/sgx-lkl.git 
cd sgx-lkl 
git checkout oe_port
.azure-pipelines/scripts/checkout_submodules.sh 
.azure-pipelines/scripts/install_prerequisites.sh 
.azure-pipelines/scripts/install_openenclave.sh 
source /opt/openenclave/share/openenclave/openenclaverc
DEBUG=true make 
source /opt/openenclave/share/openenclave/openenclaverc 
sudo -E make install  
export PATH=$PATH:/opt/sgx-lkl/bin 
/opt/sgx-lkl/bin/sgx-lkl-setup  

**Then I run basic tests like that:**
- Go under /sgx-lkl/tests/basic/sleep
- Modify Makefile and add SGXLKL_ETHREADS=1 to the beginning of SGXLKL_ENV
- Run "make run-hw"
- This doesn't fail every time. But if you run 5-10 times you will hit the bug.

**Comment by SeanTAllen** [comment]
That should install the kernel module.

@hukoyu which git sha did that build openenclave from?

**Comment by hukoyu** [comment]
@SeanTAllen 
https://github.com/lsds/sgx-lkl/blob/oe_port/.azure-pipelines/scripts/install_openenclave.sh#L10
git clone -b feature/sgx-lkl-support https://github.com/openenclave/openenclave.git

**Comment by SeanTAllen** [comment]
@hukoyu that checks out a branch, which commit is that branch currently pointing to in your checkout?

**Comment by hukoyu** [comment]
@SeanTAllen https://github.com/openenclave/openenclave/commit/8fec3caf5acae75cd4657557d20f70d7e072f0ae

**Comment by davidchisnall** [comment]
This error is being raised from `posix-host.c` in the timer code.  The timer code is intended to deliver the equivalent of timer interrupts to the bottom of the Linux kernel.  It's a bit horrible at the moment because, rather than creating a list of timers and firing them in sequence, it creates an lthread for each timer and then makes that thread sleep on a futex for the specified delay.

I think that there's actually an error in the code here.  We're not clearing `next_delay_ns` before the callback, so when we hit the call back to `timer_set_oneshot` it will hit the assert.

**Comment by SeanTAllen** [comment]
It apepars that I'm one commit behind for openenclave. It's possible that that https://github.com/openenclave/openenclave/commit/8fec3caf5acae75cd4657557d20f70d7e072f0ae introduced an issue.

**Comment by hukoyu** [comment]
cc @davidchisnall @prp @jxyang 
To fix this issue PR https://github.com/lsds/sgx-lkl/pull/341 is merged and tested in sgx-lkl nightly pipeline https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=537&view=results


**We still see failures due to this issue:**
- It fails more in run-hw and rarely happens in run-sw but still happens.

1) debug & hw: 6 failures
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=8100&_a=resultQuery

2) debug & sw: 0 failures

3) nonrelease & hw : 15 failures
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=8152&_a=resultQuery

4) nonrelease & sw : 1 failure
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=8154&_a=resultQuery

**Sample error log:**
[   SGX-LKL  ] SGX-LKL (OE) Git version 6c10f1c-dirty LKL version 5.3.0 [DEBUG build (-O0)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=4 ETHREADS=1 CMDLINE="mem=32M"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='sgxlkl-miniroot-fs.img', mnt='/', [RW   ])
[   SGX-LKL  ] No tap device specified, networking will not be available.
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-debug/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] wg0 has public key CSNZaX4rC32Rmn6jLCn1i1r3Wd3/OAQ+FVJsnO3NJ2s=
[[  SGX-LKL ]] FAIL: Bug: next_delay_ns already set for timer
[   SGX-LKL  ] init (0: 19 exit=0) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (ethread_id=0 result=19 (OE_ENCLAVE_ABORTING))
make: *** [run-hw] Error 1

**Comment by davidchisnall** [comment]
Thanks. Are you able to reproduce these in a way that would give a stack trace? I think that the assert is now correct in the timer logic, so there is likely a bug in the caller.

**Comment by SeanTAllen** [comment]
I have a fix for this. PR is coming.

**Comment by SeanTAllen** [comment]
@hukoyu this has been merged.

**Comment by hukoyu** [comment]
Sean's PR https://github.com/lsds/sgx-lkl/pull/372 fixed this bug.  I verified all this bug related tests passed. 
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_build/results?buildId=576&view=results
