### ISSUE TITLE
If sgx-lkl-run-oe process hangs after a timedout test test run script exits

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#336]
When a core test times out after 5 minutes and sgx-lkl-oe is still hanging around, pipeline test run script doesn't continue and rest of the tests are not run:

AzDevOps  75716  197  0.0      0     0 ?        RN   00:09   9:39 [sgx-lkl-run-oe]
AzDevOps  76186  0.0  0.0  14856  1060 ?        SN   00:14   0:00 grep sgx-lkl-run-oe

https://github.com/lsds/sgx-lkl/blob/oe_port/.azure-pipelines/scripts/test_runner.sh#L27
https://github.com/lsds/sgx-lkl/blob/oe_port/.azure-pipelines/scripts/test_utils.sh#L26

Instead of exiting and not running remaining tests, we should kill hanging sgx-lkl-run-oe process and let the test run script continue to run remaining tests.

**Comment by hukoyu** [comment]
Here is a link to a sample pipeline run job with this issue: 
https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=491&view=logs&j=fe3b6e0d-c167-5b41-87de-7abc79e7e1d7&t=e462892c-9357-502e-648c-9a324ddcd30e&l=306

https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=7028&_a=resultQuery

**Comment by letmaik** [comment]
`timeout` first sends SIGTERM and if that doesn't work SIGKILL. I'm not sure what else you could do.

**Comment by hukoyu** [comment]
Fixed with PR https://github.com/lsds/sgx-lkl/pull/337
