### ISSUE TITLE
Does SGX-LKL support multi-threaded applications?

### ISSUE THREAD

**Issue by dimakuv** [lsds/sgx-lkl#35]
I am confused whether SGX-LKL supports multi-threaded applications.

On the one side, from the presentation I found online, it looks like there is a SCONE-like user-level M:N threading support.

On the other side, the original paper on LKL has this quote: `Even though we do not need to implement support for user processes...`. The Google paper "User Space TCP - Getting LKL Ready for the Prime Time" has this quote: ` ...LKL is anyway a uniprocessor architecture`.

So does it mean that SGX-LKL supports multi-threaded applications but effectively multiplexes all app threads onto one host-kernel thread (M:1 model)? Or am I misunderstanding the quotes on LKL, and it actually supports multi-core architectures and thus saturates all cores?

**Comment by cpriebe** [comment]
Yes, SGX-LKL has basically the same user-level M:N threading model as SCONE. LKL itself is not used for the creation/management of user-level application threads. It is true though that the current version of LKL is implemented as a "uniprocessor" architecture without SMP support. What that means for SGX-LKL is that the in-enclave kernel will handle only one (non-blocking) system call at a time. But application threads doing other work can still run concurrently.

**Comment by dimakuv** [comment]
Thanks for the detailed answer!

I am not sure what you mean by this remark on "non-blocking syscall". What happens to blocking syscalls like `epoll` or `nanosleep`? What happens when two app threads issue two syscalls (either blocking or non-blocking)?

**Comment by cpriebe** [comment]
In case of blocking calls like `epoll` or `nanosleep` the current thread will block at which point other threads will be able to call into the kernel without an issue.

When multiple application threads issue system calls, only one will be handled by the kernel at a time and the others will block until the previous thread's call returns.

All of that said, we are actively looking into re-adding SMP support into (SGX-)LKL as this obviously can be an issue for I/O-bound multi-threaded applications. We have started working on this, based on previous work (https://github.com/Rover-Yu/lkl-linux), see https://github.com/lsds/lkl/tree/lkl-4.17-smp-support.

**Comment by dimakuv** [comment]
Thanks, Christian! Would be great to see SMP support in SGX-LKL. I will close this issue.
