### ISSUE TITLE
Allow limited forwarding of host environment variables

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#352]
Currently, all environment variables have to be specified in the app config. This prevents certain lift-and-shift deployment scenarios where some configuration is supplied in k8s yaml files. We should allow using host variables and extend the docs to make it clear that they are insecure.

In order for attestation/key release to have a chance to check that only a certain set of whitelisted variables are read from the host, the app config should be extended, e.g.:
```json
"host_env": ["VAR1", "VAR2"]
```

Dependencies:
- https://github.com/lsds/sgx-lkl/issues/207

**Comment by davidchisnall** [comment]
@wintersteiger, I think you fixed this with the attested config?

**Comment by wintersteiger** [comment]
That's right, this is covered by the new [host_import_env](https://github.com/lsds/sgx-lkl/blob/12456657c01b039405960b64dc30b398294988d7/tools/schemas/enclave-config.schema.json#L511) setting. In debug mode a few tracing variables ([these](https://github.com/lsds/sgx-lkl/blob/12456657c01b039405960b64dc30b398294988d7/src/main-oe/sgxlkl_params.c#L3)) are automatically added to that list.
