### ISSUE TITLE
Remove sgx-lkl-disk --alpine

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#368]
I think `--alpine` is redundant given that the tool can convert Docker images as well. I suggest to remove it and change all tests and samples that still use it to `--docker`. This will remove one more thing that has to be understood and explained.

**Comment by prp** [comment]
I think the benefit of `--alpine` is that it allows you to quickly create a disk image with a given application without having to create (and understand) a Dockerfile. I would keep it.

**Comment by letmaik** [comment]
I understand the value, but it's very specific and doesn't allow much customization. I think it's only good for SGX-LKL developers. Endusers would be happier to see a Dockerfile, as that's what the world is used it. I would remove it. And the fact that you have to create an extra file is not a good reason to keep it I think.

**Comment by prp** [comment]
It's useful when a user wants to try out SGX-LKL quickly with a specific application that they have in mind, without faffing with Dockerfiles.

**Comment by letmaik** [comment]
Most common applications have ready-made Docker images on Docker hub. e.g. `nginx:alpine`, and I think relying on those images is better as they may have additional configuration/samples already in the image, compared to the Alpine package manager packages.
EDIT: And in that case you wouldn't need to write a Dockerfile.

**Comment by prp** [comment]
Sure, that makes sense. But this will also require some testing that we have sufficient support that these third-party containers will just work out-of-the-box when somebody wants to try them quickly. At least with the Alpine distribution, we have a concrete set of binaries that we know can be invoked directly (and thus tested easily). As you say, nobody would use these binaries for an actual deployment, but it is useful if you want to quickly try running say a Perl script.

**Comment by letmaik** [comment]
I don't buy the "quick" argument. As long as you have a template to copy from there shouldn't be a difference in time, maybe 20 seconds, at the expense of having something that you can't extend, but have to start over in Docker.

**Comment by letmaik** [comment]
And regarding testing of third-party containers, definitely, but I see that as a good thing. The more production scenarios (=Docker) we test, the better. We should have a nightly pipeline that just tests 50 common Docker containers.

**Comment by letmaik** [comment]
We discussed this offline and came to the conclusion that SGX-LKL can be seen from two perspectives, first as the raw runtime which really just supports disk images, and then second as a package (runtime + tooling) that can be used in high-level workflows involving Docker images or other ways (`--alpine`, tar archives etc.) to produce disk images. Forcing Docker as primary high-level workflow isn't right but should be the suggested option. Different scenarios may require using different ways to produce disk images.
With that in mind this issue becomes a documentation issue and I'll open a separate issue (or re-purpose #369) for that.
