### ISSUE TITLE
SIGSEGV Error

### ISSUE THREAD

**Issue by melbek** [lsds/sgx-lkl#37]
Hi All,

I'm writing a Java Application to create a TLS Socket Server, which is working fine without sgx but makes problems with sgx-lkl.
The non-TLS socket was working out of the box, but for the TLS version I had to copy multiple files into the sgx image (nss.cfg, libnss3.so, libnssutil3.so, libplc4.so, libplds4.so, libnspr4.so).
After the last library libnspr4.so I got following error:

```shell
[    SGX-LKL   ] Warning: The application requires thread-local storage (TLS), but the current system configuration does not allow SGX-LKL to provide full TLS support in hardware mode. See sgx-lkl-run --help-tls for more information.
OpenJDK 64-Bit Server VM warning: Can't detect initial thread stack location - find_vma failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000ace6, pid=1, tid=0x00007f03672092e0
#
# JRE version: OpenJDK Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.3.0
# Distribution: Custom build (Thu Jul  6 09:24:47 UTC 2017)
# Problematic frame:
# C  0x000000000000ace6
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
Unexpected exit reason from signal handler.
/usr/local/bin/sgx-lkl-java: Zeile 29:  6256 Speicherzugriffsfehler  (Speicherabzug geschrieben) env LD_LIBRARY_PATH=${JRE_LIB_PATH} ${SGX_LKL_OPTIONS} ${SGX_LKL_RUN_EXEC} ${DISK_IMAGE} /opt/j2re-image/bin/java ${DEFAULT_JRE_ARGS} ${ARGS}
```

Can someone please help me to find out how to proceed further to find the error?
I don't know where to look for further error messages or something.

My machine is an Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-46-generic x86_64).
I will give you all the details you need.

Thank you in advance!

**Comment by cpriebe** [comment]
Hi @melbek,

When you say you had to copy in those libraries where do they come from? Are those self-compiled or do they come from the Alpine package repository?

**Comment by melbek** [comment]
Hi @cpriebe,

Thanks for your reply. Yeah the last file was the problem, I mixed it up with the file from my Ubuntu system. I installed alpine on a VM, installed openjdk8-jre and than copied the needed files to my machine. It resolved the error, but I got Exceptions indicating wrong versions between the libraries OpenJDK 8.121.13-r0 wants and the one I got installed (8.201.08-r1).

What are the steps to create a customized jre archive with the required libraries included?

**Comment by cpriebe** [comment]
There is no need to do any of that if the libraries are available via the Alpine package repository. 

All you should have to do is something like this:

```
mkdir -p java-root/app
javac apps/jvm/helloworld-java/HelloWorld.java
cp apps/jvm/helloworld-java/HelloWorld.class java-root/app
./tools/sgx-lkl-disk create --size=500M --alpine="openjdk8-jre nss nspr" --copy=./java-root sgxlkl-java.img
./tools/sgx-lkl-java ./sgxlkl-java.img HelloWorld
```

Obviously you would replace HelloWorld with your own app and dependencies. `sgx-lkl-java` is just a wrapper around `sgx-lkl-run` to set some SGX-LKL and JVM parameters. Depending on what you want to run you might have to adjust them.

**Comment by cpriebe** [comment]
Also, since you mention OpenJDK 8.121.13-r0. Make sure you use the latest version of SGX-LKL which works with the official Alpine OpenJDK8 JRE.

```
git pull
git submodule update
```

**Comment by cpriebe** [comment]
I'm closing this for now as I assume the original issue has been resolved. If this is not the case, feel free to reopen.
