### ISSUE TITLE
lkl_virtio_netdev_add ignores errors

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#370]
- Return code of `lkl_virtio_dev_setup()` is not checked.
- Return code of `dev_register()` is checked but only leads to `sgxlkl_info(..)` on error.

**Comment by davidchisnall** [comment]
@prp, I thought you fixed this one?

**Comment by prp** [comment]
@davidchisnall no, cleaning up the error handling throughout the virtio code is still outstanding. I only did the minimum amount of work to fix https://github.com/lsds/sgx-lkl/issues/491.
