### ISSUE TITLE
virtio_process_one() ignores error during queueing

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#375]
https://github.com/lsds/sgx-lkl/blob/a674a8f6c6479fbfcb8578aded364b188c6b933e/src/host_interface/virtio.c#L233-L256

`enqueue()` returns a negative number if the request has not been queued and needs to be retried later.

Also, `virtio_process_one()` is supposed to return a status which actually gets checked in `virtio_process_queue`. That is probably meant to be the status from `enqueue()`.

**Comment by prp** [comment]
Addressed by #501
