### ISSUE TITLE
virtio_net_fd_net_free() unused

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#376]
https://github.com/lsds/sgx-lkl/blob/a674a8f6c6479fbfcb8578aded364b188c6b933e/src/host_interface/virtio_netdev.c#L233-L237

Should probably be called from somewhere?

**Comment by davidchisnall** [comment]
In theory, though we currently just exit the host process to clean all of this up. If we want to be able to run multiple enclaves in a single process, this will need fixing.

**Comment by prp** [comment]
Fixed by #511
