### ISSUE TITLE
execv in SGX-LKL

### ISSUE THREAD

**Issue by sudojimmy** [lsds/sgx-lkl#38]
Is it possible to do something like execv in SGX-LKL?

I tried execv and it gives me an errno 22: invalid argument. The code works in alpine docker container.
```
char *array[] = { "/bin/echo", "Hello World", 0 };
execv(array[0], array);
```

Currently we have two seperate programs and we want to run them consecutively. Since it is not able to do fork, I'm wondering if there is a way to switch current process to another program. Thanks in advance.

**Comment by cpriebe** [comment]
Hi @sudojimmy,

unfortunately SGX-LKL currently does not support `execve`. I could imagine that we implement it in the future (and I remember discussing it internally in the past), but for now it's not possible.

**Comment by sudojimmy** [comment]
@cpriebe Got it. Thank you for the quick reply!
