### ISSUE TITLE
Failed to run tests/containers/cc locally

### ISSUE THREAD

**Issue by jxyang** [lsds/sgx-lkl#394]
While investigating a pipeline failure, I couldn't run this test locally. The error message is rather useless:
```
docker run -t --rm --privileged --network=host -v /opt/sgx-lkl-debug:/opt/sgx-lkl-debug -e SGXLKL_VERBOSE=1 -e SGXLKL_KERNEL_VERBOSE=1 -e SGXLKL_TAP=sgxlkl_tap0 python-helloworld-cc --sw-debug
standard_init_linux.go:211: exec user process caused "no such file or directory"
Makefile:46: recipe for target 'run-sw' failed
```

**Comment by letmaik** [comment]
This test requires an SGX-LKL installation from the Debian package that is then mounted into the container. Should probably add a comment at the top of the test.

**Comment by jxyang** [comment]
I don't think ask users to install sgx-lkl from Debian package is the right solution. Using the package, the test case exercises the sgx-lkl bits from the package but not the local build. I used the following command to fix the problem:
```
sudo -E make PREFIX=/opt/sgx-lkl-debug install
```
Yes, we should document this.

**Comment by jxyang** [comment]
Even though I can run the other CC based tests such as `tests/basic/overlay`,  I am still have trouble with `tests/containers/cc`. The error message is the same as above. I am on the latest oe_port branch.

**Comment by letmaik** [comment]
The Debian package contains a stand-alone distribution including bundled libraries that's suitable for mounting into a Docker container. Your local install isn't the same. See the .azure-pipelines/scripts/create_standalone_deb_pkg.sh script to create such a stand-alone package. It may be worth pulling this out of the CI scripts to allow easier local testing from a source build. Not necessarily the building of the deb package, but just the fix-up of the libraries (rpath etc.).

**Comment by letmaik** [comment]
Tracking this in https://github.com/lsds/sgx-lkl/issues/422. Feel free to submit a PR for that, otherwise I can also do that.
