### ISSUE TITLE
Update README.md file to install curl and openjdk-8-jdk before building helloworld-java

### ISSUE THREAD

**Issue by lshacham** [lsds/sgx-lkl#4]
When trying to build helloworld-java build fails twice:

Error 1:
...
/bin/sh: 1: curl: not found

Fix: 

sudo apt-get install curl

Error 2: 
...
make: javac: Command not found

Fix: 

sudo apt-get install openjdk-8-jdk

**Comment by cpriebe** [comment]
Thanks for reporting this, Liron! I added these as prerequisites to the README file in https://github.com/lsds/sgx-lkl/commit/0359c84f4d5efcb8d7a47179b07b7d9030295991.
