### ISSUE TITLE
SIGILL when trying to run a golang program

### ISSUE THREAD

**Issue by msuess** [lsds/sgx-lkl#40]
I managed to make a go app run in simulation mode, but when I run it in SGX debug mode the application crashes with a `SIGILL`. I've traced the error  to golang's `runtime/sys_linux_amd64.s`:

```
// set tls base to DI
TEXT runtime·settls(SB),NOSPLIT,$32
#ifdef GOOS_android
        // Same as in sys_darwin_386.s:/ugliness, different constant.
        // DI currently holds m->tls, which must be fs:0x1d0.
        // See cgo/gcc_android_amd64.c for the derivation of the constant.
        SUBQ    $0x1d0, DI  // In android, the tls base
#else
        ADDQ    $8, DI  // ELF wants to use -8(FS)
#endif
        MOVQ    DI, SI
        MOVQ    $0x1002, DI     // ARCH_SET_FS
        MOVQ    $SYS_arch_prctl, AX
        SYSCALL                                                     // <---- CRASH
        CMPQ    AX, $0xfffffffffffff001
        JLS     2(PC)
        MOVL    $0xf1, 0xf1  // crash
        RET
```

This function is called during golang's startup and makes an arch_prctl system call passing ARCH_SET_FS as an argument to set a base for the FS segment register.

Is this something that is supported by sgx-lkl or is it a bug?

**Comment by cpriebe** [comment]
`SYSCALL` is considered an illegal instruction within Intel SGX enclaves (see https://software.intel.com/en-us/node/703005 for a full list) as it invokes an OS-specific handler on a higher privilege level. Typically SGX-LKL makes use of the fact that most executables are dynamically against a libc implementation, more specifically musl, and go through libc to invoke system calls. Either via the `syscall` macro or indirectly by invoking some libc function that performs a system call. This allows us to intercept system calls and redirect them to the in-enclave library OS of SGX-LKL. If the application, here the go runtime, invokes the `SYSCALL` instruction directly, we don't really get an opportunity to intercept the system call request. The result is the `SIGILL` you see here.

We have recently discussed this internally. It would likely be possible to intercept the illegal instruction exception, re-enter the enclave to handle the system call request, exit again to return from the signal handling code, and then continue execution within the enclave. This would potentially be okay if the `SYSCALL` instruction is used infrequently, but it would have a significant impact on performance if they were more frequent as you can imagine. As far as I understand, go programs by default do not link against libc at all, so I would not expect them to run with SGX-LKL. So to summarise, running code like the example you give above is not supported by SGX-LKL right now.

I am surprised the program runs in simulation mode. A `SYSCALL` instruction in simulation mode would bypass the syscall interception described above and would be handled by the host OS instead. I assume SGX-LKL is largely getting bypassed in this case.

**Comment by prp** [comment]
Just to add: you could try replacing the direct `SYSCALL` instruction with a call to the libc `syscall` macro and recompile the Go runtime system. The libc `syscall` macro will be handled by SGX-LKL.

**Comment by msuess** [comment]
Thank you for your thorough explanation! Closing this issue.
