### ISSUE TITLE
JDK 11 Support?

### ISSUE THREAD

**Issue by kant111** [lsds/sgx-lkl#42]
JDK 11 Support? The memory footprint is already much lower than 8.

**Comment by cpriebe** [comment]
Hi @kant111,

Until very recently there were no official musl/Alpine-based builds of JDK11. It seems like this has changed with Alpine 3.10? I can see there is an Oracle OpenJDK 11 package here: https://pkgs.alpinelinux.org/package/v3.10/community/x86_64/openjdk11

The OpenJDK8 version available in the Alpine package repositories is an IcedTea build and runs with SGX-LKL without modifications. I have done some quick test with the openjdk11-jre-headless package but couldn't get it to run right away.

We have a few other things to work on right now, but when I have a bit of free time I might take a look at this.
