### ISSUE TITLE
Integrate sgx-lkl-gdb with SGX-LKL source tree and Debian packages

### ISSUE THREAD

**Issue by prp** [lsds/sgx-lkl#424]
Currently the `sgx-lkl-gdb` tool relies on an Open Enclave install under `/opt/openenclave` on the host. We will no longer assume that such an installation exists.

Proposed changes:

1. `sgx-lkl-gdb` should be included in the Debian packages
2. The behaviour of sgx-lkl-gdb should be changed as follows:
     - if `sgx-lkl-gdb` is invoked from the SGX-LKL source tree, it should use the OE version installed as part of the build tree for gdb support.
     - `sgx-lkl-gdb` in the Debian package should be self-contained, i.e., it should provide all dependencies as part of the package (e.g., the OE gdb `ptrace` library and the gdb Python plugin).

cc: @letmaik

**Comment by letmaik** [comment]
@prp For some reason the "fixes xx" GitHub syntax in PRs doesn't seem to close issues (anymore?). Is there something in the repo settings we need to change?
