### ISSUE TITLE
Kernel version mismatch while enabling module installed from FSGSBASE DKMS driver inside Docker container

### ISSUE THREAD

**Issue by glorysdj** [lsds/sgx-lkl#435]
Follow the readme in branch oe_port, I have problem to install or build sgx-lkl-oe.

Error occurs when "The FSGSBASE DKMS driver can be installed with:"
```
sudo apt install enable-fsgsbase-dkms
echo "enable_fsgsbase" | sudo tee -a /etc/modules
sudo modprobe enable_fsgsbase
```
apt install enable-fsgsbase-dkms will install enable-fsgsbase-dkms to /lib/modules/4.15.0-106-generic/updates/dkms/enable_fsgsbase.ko
So modprobe enable_fsgsbase always fail, since it will find enable_fsgsbase from /lib/modules/4.15.0-72-generic.
When try to "modprobe enable_fsgsbase" from /lib/modules/4.15.0-106-generic, error "Exec format error" happens.

Please help to fix.

BTW, Is there a Docker way to build and deploy apps like master branch?

Thanks!

**Comment by letmaik** [comment]
Could you please paste the complete terminal output?

**Comment by glorysdj** [comment]
apt install enable-fsgsbase-dkms
```
Loading new enable_fsgsbase-0.1.5 DKMS files...
It is likely that 4.15.0-72-generic belongs to a chroot's host
Building for 4.15.0-106-generic
Building for architecture x86_64
Building initial module for 4.15.0-106-generic
Done.

enable_fsgsbase:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.15.0-106-generic/updates/dkms/

/etc/modprobe.d/dkms.conf: added 'options enable_fsgsbase val=1'
depmod...

DKMS: install completed.
Setting up dirmngr (2.2.4-1ubuntu1.2) ...
Setting up build-essential (12.4ubuntu1) ...
Setting up gpg-wks-client (2.2.4-1ubuntu1.2) ...
Setting up gnupg (2.2.4-1ubuntu1.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
```

modprobe enable_fsgsbase
```
modprobe: FATAL: Module enable_fsgsbase not found in directory /lib/modules/4.15.0-72-generic
```

**Comment by letmaik** [comment]
What's the output of `cat /proc/version`?

**Comment by glorysdj** [comment]
Linux version 4.15.0-72-generic
BTW I run all these in a Docker container, is that a issue?

**Comment by letmaik** [comment]
Yes, that is not supported. You need to install the kernel driver on the host, not inside Docker.

**Comment by glorysdj** [comment]
if i run all these in a host machine, sgx-lkl-setup will get error, "insmod: ERROR: could not insert module /opt/sgx-lkl/bin/../tools/kmod-set-fsgsbase/mod_set_cr4_fsgsbase.ko: Invalid module format"


cat /proc/version
```
Linux version 4.15.0-88-generic (buildd@lgw01-amd64-036) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
```

sgx-lkl-setup
```
Creating tap network device for SGX-LKL...Done
Updating host networking to forward traffic from SGX-LKL to the public host interface...Done
Setting up Linux kernel module to support userspace FSGSBase...
insmod: ERROR: could not insert module /opt/sgx-lkl/bin/../tools/kmod-set-fsgsbase/mod_set_cr4_fsgsbase.ko: Invalid module format
[4521362.562706] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #82, CR4 before: 0x007606e0, after: 0x007706e0.
[4521362.562709] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #91, CR4 before: 0x007606e0, after: 0x007706e0.
[4521362.562712] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #89, CR4 before: 0x007606e0, after: 0x007706e0.
[4521362.562716] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #72, CR4 before: 0x007606e0, after: 0x007706e0.
[4521362.562719] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #79, CR4 before: 0x007606e0, after: 0x007706e0.
[4521362.562722] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #95, CR4 before: 0x007606e0, after: 0x007706e0.
[4521362.562725] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #83, CR4 before: 0x007606e0, after: 0x007706e0.
[4521362.562729] SGX-LKL: Successfully set CR4.FSGSBASE to 1 on CPU #78, CR4 before: 0x007606e0, after: 0x007706e0.
[4521374.541494] IPv6: ADDRCONF(NETDEV_UP): sgxlkl_tap0: link is not ready
[4521374.620617] mod_set_cr4_fsgsbase: version magic '5.0.0-1025-azure SMP mod_unload ' should be '4.15.0-88-generic SMP mod_unload '
Done
```

**Comment by glorysdj** [comment]
> Yes, that is not supported. You need to install the kernel driver on the host, not inside Docker.

ok. Thanks @letmaik 

please help to check above issue.

And is there a Docker way to build and deploy apps like the master branch?

**Comment by letmaik** [comment]
Right, please ignore the error. The sgx-lkl-setup script shouldn't try to install the kernel module, in fact it shouldn't even be part of the Debian package.

Docker support is undergoing some redevelopment and is not ready yet.

**Comment by glorysdj** [comment]
> Right, please ignore the error. The sgx-lkl-setup script shouldn't try to install the kernel module, in fact it shouldn't even be part of the Debian package.
> 
> Docker support is undergoing some redevelopment and is not ready yet.

so, that means i have isntalled sgx-lkl successfully now?

**Comment by letmaik** [comment]
Yes.

**Comment by letmaik** [comment]
I'm going to track this in #437 and #438. Thanks.
