### ISSUE TITLE
Add unit test for sgx-lkl-gdb

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#442]
This can be a crash test or something more clever.

**Comment by prp** [comment]
This looks more like P2 or P3.

**Comment by bodzhang** [comment]
Debugging experience is important for SGX-LKL usage development as well as for the SGX-LKL project community members' productivity.

**Comment by letmaik** [comment]
The linked PR should have closed this issue but didn't. If the unit test is not good enough, please open a new issue with details on what's missing.
