### ISSUE TITLE
Fix dotnet test: Couldn't find a valid ICU package installed on the system

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#458]
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /usr/bin/dotnet
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
Aborted
[[  SGX-LKL ]] lkl_terminate(): terminating LKL (exit_status=134)
Aborted
Aborted
[[  SGX-LKL ]] lkl_termination_thread(): termination thread unblocked
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_sys_chdir(/)
Aborted
Aborted
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_umount_timeout(/)
[    1.212851] EXT4-fs (vda): re-mounted. Opts: (null)
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_virtio_netdev_remove()
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_sys_halt()
[    1.212851] reboot: Restarting system
[[  SGX-LKL ]] lkl_termination_thread(): lthread_detach2() done
Makefile:36: recipe for target 'run-sw' failed
make run-sw: FAILED WITH EXIT CODE: 2
Test run completed with EXIT CODE 2

**Comment by wintersteiger** [comment]
Which branch are you working with? Just minutes ago I fixed exactly this issue in my attested config branch, where the underlying issue was that `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` was not imported from the host.

**Comment by hukoyu** [comment]
@wintersteiger oe_port branch. I submitted PR 459 and waiting result.

**Comment by hukoyu** [comment]
@wintersteiger  https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=774&view=results
All 4 VMs running core tests stopped responding to CI pipeline, I think they crashed/rebooted. This looks related to https://github.com/lsds/sgx-lkl/issues/456

cc @letmaik @davidchisnall @jxyang

**Comment by wintersteiger** [comment]
Yes, you need to rebase onto `oe_port` (or merge it) to disable the test that kills the CI VMs.

**Comment by hukoyu** [comment]
PR 459 merged and fix verified.
