### ISSUE TITLE
IAS API subscription keys support

### ISSUE THREAD

**Issue by fixerivan** [lsds/sgx-lkl#47]
version 3 of the Attestation API switched from user certificate authentication to API subscription keys

does sgx-lkl support API subscription keys? couldn't find any reference to this anywhere

thanks!

**Comment by cpriebe** [comment]
Hi @fixerivan,

No, support for this has unfortunately not been added yet.

**Comment by fixerivan** [comment]
thanks, lets hope intel wont shut down the v3 api anytime soon :)
