### ISSUE TITLE
Error: crypt_load(): No error information (-22)

### ISSUE THREAD

**Issue by fixerivan** [lsds/sgx-lkl#56]
following "Full attestation and remote launch example" from wiki

on the client side:

sgx-lkl-ctl --server=10.0.1.1:56001 run --app=sgxlkl.redis.conf
Connecting to 10.0.1.1:56001... done.
[    SGX-LKL   ] Request successful.

on the server side:

SGXLKL_VERBOSE=1 SGXLKL_TAP=sgxlkl_tap0 SGXLKL_REMOTE_CONFIG=1 SGXLKL_REPORT_NONCE=1086786471072294837                                                                                                                        1 SGXLKL_IAS_SPID=91335C178CFD2623B9F1965D907B2D72 SGXLKL_IAS_KEY_FILE=/root/client.key SGXLKL_IAS_CERT=/root/client.                                                                                                                        crt SGXLKL_IAS_QUOTE_TYPE=1 SGXLKL_REMOTE_CMD_ETH0=1 SGXLKL_WG_PEERS='HsDGWBSmfODurz++XsTJfk+ctoKTahiGpvXRkzTx6Wc=:10                                                                                                                        .0.2.2/32:10.0.1.254:56002' sgx-lkl-run ./disk.img
[    SGX-LKL   ] Maximum enclave threads (TCS): 8
[    SGX-LKL   ] Kernel command line: ""
[    SGX-LKL   ] Adding entropy to entropy pool.
[    SGX-LKL   ] wg0 has public key FiW4ynEn5HzUU/sX2DyzrJCUvHrd3xrUxFok2qyeXDY=
[    SGX-LKL   ] Enclave report nonce: 10867864710722948371
[    SGX-LKL   ] Received quote from launch enclave:
[    SGX-LKL   ]  MRENCLAVE: 6a7f2542b409ff038bc9b93907ba3a06b237e5f1b96244ce116140dcae0fa9e2
[    SGX-LKL   ]  MRSIGNER:  6fd82723204c46f5aee8d207c82c59b4afa1ede1a5d0fcebd2274fa48d60eac7
[    SGX-LKL   ] Sending IAS request...
[    SGX-LKL   ] Intel Attestation Service Response:
[    SGX-LKL   ]  Quote status: GROUP_OUT_OF_DATE
[    SGX-LKL   ]  EPID group flags: 0x4
[    SGX-LKL   ]  TCB evaluation flags: 0x09
[    SGX-LKL   ]  PSE evaluation flags: 0x00
[    SGX-LKL   ]  One or more advisories apply to the attested platform. Refer to https://security-center.intel.com f                                                                                                                        or more information:
[    SGX-LKL   ]   INTEL-SA-00233,INTEL-SA-00161
[    SGX-LKL   ] Starting attestation server, listening on 10.0.1.1:56000...
[    SGX-LKL   ] Starting remote control server, listening on 10.0.1.1:56001...
[    SGX-LKL   ] Waiting for application run request...
**Error: crypt_load(): No error information (-22)**
[    SGX-LKL   ] Set working directory /

**Comment by cpriebe** [comment]
Presumably the correct key for the disk decryption is provided as part of the application configuration file? What happens when you try to run an application from the same disk via `sgx-lkl-run <disk> <command> and specify the key via `SGXLKL_HD_KEY=<keyfile>`? I assume you get the same error?

**Comment by fixerivan** [comment]
interestingly this works:

root@vitro ~ # sgx-lkl-disk create --size=50M --encrypt --key-file --integrity --alpine="" sgxlkl-disk.img.enc.int
Creating base image from Alpine with packages ...
Reusing cached Alpine miniroot image /root/.cache/sgxlkl/alpine-minirootfs-3.8.2-x86_64.tar.gz...
Verifiying checksum of /root/.cache/sgxlkl/alpine-minirootfs-3.8.2-x86_64.tar.gz...
Creating disk image file...
Updating Alpine package index...
Installing
OK: 4 MiB in 13 packages
Encrypting sgxlkl-disk.img.enc.int...
  Cipher: aes-xts-plain64
  Key size: 256
  Hash Algorithm: sha256
  Integrity: hmac-sha256
  PBKDF: pbkdf2
Generating new key file sgxlkl-disk.img.enc.int.key of size 64 bytes...
Using key file sgxlkl-disk.img.enc.int.key for disk encryption...
Creating encrypted disk...
Formatting encrypted disk...
Opening encrypted disk...
Copying base image to encrypted disk...
Cleaning up temporary files...
root@vitro ~ # SGXLKL_HD_KEY=./sgxlkl-disk.img.enc.int.key sgx-lkl-run ./sgxlkl-disk.img.enc.int /bin/echo "Hello World"
Hello World

will have to debug the remote scenario more ... thx

**Comment by cpriebe** [comment]
You can also test your application configuration file via

```
sgx-lkl-run --app=<appconfig> <disk>
```

**Comment by cpriebe** [comment]
I'm going to close this for now. Feel free to reopen if this issue still exists.
