### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by fixerivan** [lsds/sgx-lkl#57]
following the redis example from wiki: "Running applications from the Alpine Linux repository"

I noticed that sgx-lkl-run "eats" all the CPU time it can get

![image](https://user-images.githubusercontent.com/29037777/61245187-3a5c6e80-a74c-11e9-92b9-6a87b99cf85c.png)

stracing seams to indicate aggressive ioctl / nanosleep loops

is there anything that can be done to reduce idle cpu usage? the redis sample is not actually doing anything ... thx

**Comment by cpriebe** [comment]
There is definitely a lot of potential for optimising this. For now, what you can already do is to specify how often enclave threads should spin when looking for something to do before going to sleep, and for how long they should go to sleep via `SGXLKL_ESPINS` and `SGXLKL_ESLEEP`. This should help to reduce the CPU usage.
