### ISSUE TITLE
Encrypting disk image using a sealed key

### ISSUE THREAD

**Issue by kladkogex** [lsds/sgx-lkl#59]
I am looking to use not the plaintext version by a sealed version of disk encyption key.

Basically :

0. Key is initially generated inside the encave and used to encrypt disk image.

1. Sealed key is input into the enclave by the user

2. Enclave unseals the key.

3. The plain text key is used to decrypt the disk image.

My question is - which modifications would I need to make to enable this? I would be happy to contribute them back

**Comment by cpriebe** [comment]
Hi @kladkogex,

Apologies for the late response! I am not entirely sure if I understand the issue correctly but this seems to be quite close to the general remote attestation process:

1. You create an encrypted disk on a trusted client
2. You launch SGX-LKL and provide it with the disk image (but not the key)
3. You perform remote attestation
4. If the remote attestation was successful, you can provide the disk encryption key remote via a secure connection
5. SGX-LKL can then mount and decrypt the disk image, load the application, and run it.

You can find more information on remote attestation with SGX-LKL here: https://github.com/lsds/sgx-lkl/wiki/Remote-Attestation-and-Remote-Control

**Comment by cpriebe** [comment]
Closing this for now. Feel free to reopen if my comment above did not address the original issue.
