### ISSUE TITLE
deploy Docker container missing libjson-c.so.2

### ISSUE THREAD

**Issue by jjcollinge** [lsds/sgx-lkl#62]
When following the build and deploy in docker instructions on an Ubuntu 18.04 machine I get an issue.

Building LKL in docker works ok
`./sgx-lkl-docker.sh -s build`

Deploying the sample Java app using
`./sgx-lkl-docker.sh -s deploy-app jvm-helloworld`
fails with the following error:
`/sgx-lkl/build/sgx-lkl-run: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory`. I exec'd into the container to check for the existence of `libjson-c` to see if it was an `LD_LIBRARY_PATH` issue but I didn't find the library on disk.

The command being executed in the deploy container is 
`(cd /sgx-lkl/apps/jvm/helloworld-java && make) && SGXLKL_VERBOSE=1 /sgx-lkl/tools/sgx-lkl-java /sgx-lkl/apps/jvm/helloworld-java/sgxlkl-java-fs.img HelloWorld`
The disk image builds fine but executing `/sgx-lkl/tools/sgx-lkl-java` and thus `sgx-lkl-run` causes the issue.

I've put a temporary fix in by adding `libjson-c2` to the apt-get installs in the deploy Docker image which allows me to run the Java app. 
```
FROM phusion/baseimage as deploy

WORKDIR /sgx-lkl

RUN apt-get update && apt-get install -y \
  curl \
  openjdk-8-jdk-headless \
  libjson-c2 \  <--- addition
  sudo \
  make \
  && rm -rf /var/lib/apt/lists/*
...
```
As I'm new to this codebase I'm not sure if there's a better solution. If you think this is a suitable fix I'm happy to open a PR. I might also look to add the docker build to your travis CI in a separate PR.

**Comment by cpriebe** [comment]
Hey @jjcollinge,

Thanks a lot for reporting this (and thanks a lot @deadlyfingers for confirming)! I have to admit I rarely use the Docker build during development so things like these might go unnoticed. The dependency hasn't changed in a while though so I'm a little bit surprised this hasn't come up before. Which OS (version) is this on?

In any case, pull requests are very welcome and having a Docker Travis build would be a nice addition too!

**Comment by jjcollinge** [comment]
Hi @cpriebe - no worries, I do think this probably needs me to do a little more investigation to work out when/why the dependency was dropped before putting in the PR. I'm running on `Ubuntu 18.04.2 LTS`. I'll try find some time to dig into this and if I don't find anything more insightful I'll open a PR with the above fix.

**Comment by cpriebe** [comment]
I'm closing this as this should be fixed after merging pull request https://github.com/lsds/sgx-lkl/pull/74. Adding the dependency seems to be the right thing to do.

Please re-open/create a new issue if there are any issues.
