### ISSUE TITLE
src/lkl/posix-host.c contains a mix of tabs and spaces for indentation

### ISSUE THREAD

**Issue by SeanTAllen** [lsds/sgx-lkl#665]
It should be switched to all spaces.

**Comment by davidchisnall** [comment]
It is based on a file from the LKL tree and so uses the Linux coding standards.  Someone with a clang-format config has inserted some lines with spaces in them, but it should be using tabs everywhere.

**Comment by SeanTAllen** [comment]
It's using spaces almost everywhere at the moment, at least when I looked.

**Comment by davidchisnall** [comment]
It wasn't, and the upstream version wasn't, someone must have partially reformatted it.

**Comment by SeanTAllen** [comment]
I'm going to do this once #655 is merged.

**Comment by SeanTAllen** [comment]
It was decided on #711 to make spaces the default for posix-host.c like the rest of the project.
