### ISSUE TITLE
json comment will hang program execution

### ISSUE THREAD

**Issue by praenubilus** [lsds/sgx-lkl#684]
Comment is not officially supported in JSON. If comments has been put in the `enclave-config.json` file, application run through sgx-lkl-run-oe will hang at early stage, enclave init and other kernel information will not be printed out. 
sample problematic `enclave-config.json` file:
```json
{
    "args": [
        "app" // comments
    ]
}
```
The expected result should be exit w/ error code.

**Comment by SeanTAllen** [comment]
There's a PR #688 open to fix this.
