### ISSUE TITLE
LTP: 2 tests enabled in both batches. Disable from batch2

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#685]
#/ltp/testcases/kernel/syscalls/statx/statx01
#/ltp/testcases/kernel/syscalls/utime/utime04

Disable them from batch2

**Comment by hukoyu** [comment]
@shaikshavali1 can you submit a PR to disable these two tests in batch2. They are already enabled in batch1 and lets keep batch1 ones.

**Comment by shaikshavali1** [comment]
> @shaikshavali1 can you submit a PR to disable these two tests in batch2. They are already enabled in batch1 and lets keep batch1 ones.

@hukoyu, Raised a PR. Link to PR -https://github.com/lsds/sgx-lkl/pull/687.
