### ISSUE TITLE
Add scone related licensing in the legacy branch read me file 

### ISSUE THREAD

**Issue by agowdamsft** [lsds/sgx-lkl#696]
Files to mention references to scone license
 
https://github.com/lsds/sgx-lkl/blob/34b520e41de2069c24d1515bca6d40aa8eded7c8/src/sgx/sgx_sign.c
https://github.com/lsds/sgx-lkl/blob/9baedf3fa74a0b96e30a6c1fe318b020ae95012c/src/host/sgx_hostcall_interface.c
https://github.com/lsds/sgx-lkl/blob/9baedf3fa74a0b96e30a6c1fe318b020ae95012c/src/host/sgx_hostcalls.c
https://github.com/lsds/sgx-lkl/blob/master/src/sgx/sgx_enclave_config.c
https://github.com/lsds/sgx-lkl/blob/9baedf3fa74a0b96e30a6c1fe318b020ae95012c/src/host/sgx_hostcalls.c
https://github.com/lsds/sgx-lkl/blob/9baedf3fa74a0b96e30a6c1fe318b020ae95012c/src/main/sgxlkl_run.c

**Comment by davidchisnall** [comment]
I didn't see this issue because it wasn't assigned to me, but PR #701 should fix it.
