### ISSUE TITLE
Analysis of security/usability/performance

### ISSUE THREAD

**Issue by dimakuv** [lsds/sgx-lkl#71]
Hello,

I am curious if you have any techreport or a blog post with some security/performance analysis of SGX-LKL? In particular, it is interesting to know:
1. Total lines of code (and the breakdown)
2. The required effort to port Linux (LKL backend lines of code, which parts of Linux must be changed -- if any -- and how it affects performance)
3. The analysis of the virtio interface in terms of security (attack vectors)
4. Usability aspect is quite interesting -- what is required from the end user to run the app
5. Performance is also interesting -- does it e.g. stress the EPC to run the complete TCP/IP stack inside of the enclave, does it significantly increase I/O latency?

I understand that answering these questions basically requires writing a conference paper :) But any quick estimates?

**Comment by prp** [comment]
Hi Dmitrii, you may find our arXiv paper helpful: https://arxiv.org/abs/1908.11143

**Comment by dimakuv** [comment]
I didn't know you already have a paper, thanks!
