### ISSUE TITLE
Not able to write to files in the root disk image

### ISSUE THREAD

**Issue by jxyang** [lsds/sgx-lkl#713]
I modified helloworld sample so that in addition to reading from "helloworld.txt", it also writes to the file. Note the enclave_config.json file indicates this is a writable disk image:

{
  "args": [
    "app/helloworld"
  ],
  "root": {
    "readonly": false
  }
}
However, after I run the sample, and mount the disk image, file "/app/helloworld.txt" is not updated.

This seems to be blocking code coverage measurement as we can't generate the coverage data files on the disk image.

**Comment by letmaik** [comment]
Could you change the existing hello world test (or some other test) to reproduce it in CI?

**Comment by jxyang** [comment]
Sure. Let's see how it goes.

https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=1671&view=results

**Comment by jxyang** [comment]
Oops, the branch seems have a wrong submodule. Anyway, it's easy to replace helloworld with the following code and see the crash in your local env.
```
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define HW_FILE "/app/helloworld.txt"

int main(int argc, char** argv)
{
    char buf[100];
    FILE* f = fopen(HW_FILE, "rw");
    if (!f)
    {
        fprintf(
            stderr, "Could not open file %s: %s\n", HW_FILE, strerror(errno));
        fprintf(stderr, "TEST_FAILED");
        exit(1);
    }

    // Prints first line of file /app/helloworld.txt (max 100 characters)
    if (fgets(buf, sizeof(buf), f) == buf)
    {
        printf("%s", buf);
    }
    else
    {
        fprintf(
            stderr,
            "Could not read first line of file %s: %s\n",
            HW_FILE,
            strerror(errno));
        fprintf(stderr, "TEST_FAILED");
        exit(1);
    }

    fprintf(f, "blah.....");
    fclose(f);

    // jxyang: trying to create a new file
    f = fopen("/testt.txt", "rw+");
    fprintf(f, "tttttt\n");
    fclose(f);
    return 0;
}
```

**Comment by prp** [comment]
@jxyang do you get an error message, or is the file `/testt.txt` just missing? Is the file system unmounted cleanly? Does adding `fflush` make a difference? Is this a regression introduced by #697?

**Comment by jxyang** [comment]
There is a crash, caused likely by line `fprintf(f, "tttttt\n");`. In addition, "helloworld.txt" is not updated in spite of line `fprintf(f, "blah.....");`.

**Comment by hukoyu** [comment]
This is a blocker for code coverage solution since code coverage creates files in image and then extracts and processes to generated the code coverage data. 

cc @paulcallen  @bodzhang
