### ISSUE TITLE
File systems unmounted using MNT_DETACH may become inconsistent

### ISSUE THREAD

**Issue by prp** [lsds/sgx-lkl#754]
We currently unmount the root file system using the `MNT_DETACH` option, otherwise we sometimes observe hanging behaviour (despite the timeout): https://github.com/lsds/sgx-lkl/blob/a1fb63f406557cb02123682efaa48d78018a3421/src/lkl/setup.c#L1276

We should check that this always cleanly unmounts the file systems and does not lead to data loss. It also not clear that the code correctly unmounts the entire file system hierarchy.

**Comment by paulcallen** [comment]
do we know if any tests hit this issue? 
Does it need to be fixed by September? I am assuming not.

**Comment by prp** [comment]
Didn't @jxyang report that he wrote to a file in the root file system, and this wasn't persisted across SGX-LKL restarts? We should add a CI test that checks that we are persisting root file system changes correctly.

**Comment by SeanTAllen** [comment]
@prp I believe you mean: https://github.com/lsds/sgx-lkl/issues/713

**Comment by paulcallen** [comment]
anyone think this is not p2?
