### ISSUE TITLE
Timestamp inside simulated sgx enclave wrong

### ISSUE THREAD

**Issue by lead4good** [lsds/sgx-lkl#76]
For our application we need to have access to the correct timestamp. Currently the system time returns very weird values upon each call with no pattern recognizable. You can reproduce this by running e.g. ```date``` inside the miniroot container. Due to lack of sgx compatible hardware we were only able to test this inside simulated mode.

**Comment by cpriebe** [comment]
Hi @lead4good,

Thanks a lot for opening this issue. I have just tested this on my system and wasn't able to reproduce the behaviour:

```
cpriebe@x:~/sgx-lkl/apps/miniroot$ ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:12 UTC 2019
cpriebe@x:~/sgx-lkl/apps/miniroot$ ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:13 UTC 2019
cpriebe@x:~/sgx-lkl/apps/miniroot$ ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:14 UTC 2019
cpriebe@x:~/sgx-lkl/apps/miniroot$ ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:14 UTC 2019
cpriebe@x:~/sgx-lkl/apps/miniroot$ ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:15 UTC 2019
cpriebe@x:~/sgx-lkl/apps/miniroot$ ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:16 UTC 2019
[...]
cpriebe@x:~/sgx-lkl/apps/miniroot$ SGXLKL_GETTIME_VDSO=0 ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:31 UTC 2019
cpriebe@x:~/sgx-lkl/apps/miniroot$ SGXLKL_GETTIME_VDSO=0 ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:32 UTC 2019
cpriebe@x:~/sgx-lkl/apps/miniroot$ SGXLKL_GETTIME_VDSO=0 ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /bin/date
Mon Oct 28 14:59:33 UTC 2019
[...]
```

Could you say a bit more about your setup/system?

**Comment by lead4good** [comment]
The setup is a domU Xen VM running Fedora 30. With ```SGXLKL_GETTIME_VDSO=0``` I do get the correct time however. This is sufficient for me, I do believe that the problem is due to my environment, so I'm closing this issue. Thanks!

**Comment by RobertZenz** [comment]
Just as a heads-up, we're seeing the same on Ubuntu 18.04 machines. The timestamps provided are all over the place, pretty much looks like it is reading random memory, but we did not have the opportunity so far to test in a "real" enclave, only debugging.

**Comment by prp** [comment]
@RobertZenz We are working on a new version of SGX-LKL that won't have this problem. Please stay tuned.

**Comment by RobertZenz** [comment]
Great to hear.

Out of curiosity, is mechanism kinda functional or only stubbed regarding the Enclave?

**Comment by prp** [comment]
> Great to hear.
> 
> Out of curiosity, is mechanism kinda functional or only stubbed regarding the Enclave?

Are you asking about the new mechanism? The problem with using VDSO in this way is that the implementation is specific to the Linux kernel version. When there is a kernel upgrade, the layout of the VDSO page may change, breaking the support in SGX-LKL. Instead, a better design is to have a shared memory page that provides VDSO-like functionality, but is entirely under our control.

**Comment by RobertZenz** [comment]
> Are you asking about the new mechanism?

About the overall functionality. If I understood this right, the VDSO is a mechanism which allows to call kernel functions from userspace without having to switch to kernel mode. I'm a little bit fuzzy on the implementation details of SGX-LKL to be honest, so please forgive some inaccuracies, but as far as I understood it provides a LKL shim/implementation inside the enclave which can be used. If a kernel function is called, it obviously must leave the enclave to perform its action (except if you re-implemented it inside the shim). So is the VDSO mechanism actually functional, meaning that the call stays inside the enclave, or is it rather just stubbed and forwarded outside the enclave?
