### ISSUE TITLE
asylo

### ISSUE THREAD

**Issue by fixerivan** [lsds/sgx-lkl#77]
you probably know about them but is there any reason why you don't mention (https://github.com/google/asylo) in your paper? can run existing SW too: https://asylo.dev/blog/2019/asylo-redis-sqlite.html and has fork implemented using DH: * ... these properties are guaranteed by the fork() implementation via a one-time authenticated EC-based Diffie-Hellman key exchange between the two enclaves.* 

how would you compare sgx-lkl to asylo? 

thx

**Comment by prp** [comment]
Hi @fixerivan,

We are aware of Asylo, but we would regard it more as an SDK for building enclave applications (similar to OpenEnclave and the Intel SGX SDK) and not a library OS for supporting existing Linux applications/containers inside of SGX enclaves. In particular, as far as I know, Asylo cannot execute unmodified Linux binaries inside of SGX enclaves.

**Comment by fixerivan** [comment]
they claim that:

To make it easy to run an application in an enclave, Asylo now provides an
application wrapper, which enables users to easily run an existing
application in an enclave without any source code modifications.

**Comment by fixerivan** [comment]
thanks for the clarification
