### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by fixerivan** [lsds/sgx-lkl#78]
any plans of adding support for fork?

support for pre-built sw from alpine packages is quite limited without fork, almost anything i try ends with:

_fork: Function not implemented_

**Comment by prp** [comment]
Our experience has been that the majority of useful applications to run inside of SGX enclaves are single-process, so the lack of fork() is not an issue. Obviously shells and shell scripts cannot be run, but it is easy to work around this limitation.

The problem with fork() support on SGX1 hardware is that it cannot be implemented efficiently. Even if we were to provide an implementation of fork() entirely in software, the performance overhead would be so high that it is unclear that such support would actually be useful in practice.

**Comment by fixerivan** [comment]
i was thinking more about graphical applications using X server over network ...
