### ISSUE TITLE
Test failures after merging PR #403 (Lthreads disentangled from musl)

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#786]
With https://github.com/lsds/sgx-lkl/pull/765 we want to enable 15 new LTP tests.
All of these tests were passing before merging https://github.com/lsds/sgx-lkl/pull/765

After https://github.com/lsds/sgx-lkl/pull/765 merged, I rebased https://github.com/lsds/sgx-lkl/pull/765 and updated ltp submodule and in the pipeline https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=1860&view=results below tests are failing:

I will disable these tests for now in my PR.
1) renameat01
2) fchown04   
3) unshare02    
4) read02
5) fallocate01

Not part of https://github.com/lsds/sgx-lkl/pull/765 but below tests are failing:
pipe03 (This is not a patched test. This is regression)
setresui04  @KenGordon  looking into that  , I will disable this test for now
setreuid07 @KenGordon looking into that, I will disable this test for now

I will add logs of these tests below separately.

cc @vtikoo @paulcallen  @jxyang @mikbras @davidchisnall @prp

**Comment by hukoyu** [comment]
LTP Test: read02 
Debug - HW failure:
[Standard_Console_Output read02-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073022/Standard_Console_Output.read02-debug-hw.log)

Debug - SW failure:
[Standard_Console_Output read02-debug-sw.log](https://github.com/lsds/sgx-lkl/files/5073029/Standard_Console_Output.read02-debug-sw.log)

Nonrelease - HW failure:
[Standard_Console_Output read02-nonrelease-hw.log](https://github.com/lsds/sgx-lkl/files/5073039/Standard_Console_Output.read02-nonrelease-hw.log)

Nonrelease-SW failure:
[Standard_Console_Output read02-nonrelease-sw.log](https://github.com/lsds/sgx-lkl/files/5073042/Standard_Console_Output.read02-nonrelease-sw.log)

**Comment by hukoyu** [comment]
LTP Test: pipe03
Nonrelease - HW failure:
[Standard_Console_Output pipe03-nonrelease-hw.log](https://github.com/lsds/sgx-lkl/files/5073060/Standard_Console_Output.pipe03-nonrelease-hw.log)

**Comment by hukoyu** [comment]
LTP Test: fallocate01
Debug-HW failure:
[Standard_Console_Output fallocate01-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073066/Standard_Console_Output.fallocate01-debug-hw.log)

**Comment by hukoyu** [comment]
LTP Test: unshare02
Debug-HW failure:
[Standard_Console_Output unshare02-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073073/Standard_Console_Output.unshare02-debug-hw.log)

**Comment by hukoyu** [comment]
LTP Test: fchown04
Debug-HW failure:
[Standard_Console_Output fchown04-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073083/Standard_Console_Output.fchown04-debug-hw.log)

**Comment by hukoyu** [comment]
LTP Test: renameat01
Debug-HW failure:
[Standard_Console_Output renameat01-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073095/Standard_Console_Output.renameat01-debug-hw.log)

**Comment by hukoyu** [comment]
setreuid07 debug-hw failure:
[Standard_Console_Output setreuid07-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073125/Standard_Console_Output.setreuid07-debug-hw.log)

setresuid04 debug-hw failure
[Standard_Console_Output setresuid04-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073126/Standard_Console_Output.setresuid04-debug-hw.log)

These two test are also tracked by https://github.com/lsds/sgx-lkl/issues/774

**Comment by hukoyu** [comment]
I disabled  7 tests: renameat01, fchown04, unshare02, read02, fallocate01, setresuid04 and setreuid07
and pushed commit for PR https://github.com/lsds/sgx-lkl/pull/765 and pipeline failed for debug-hw only for these 5 tests:
mount04
mount06
sync_file_range02
unshare01
lgetxattr02

https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=1863&view=results

Logs:
[Standard_Console_Output mount04-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073468/Standard_Console_Output.mount04-debug-hw.log)
[Standard_Console_Output sync_file_range02-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073469/Standard_Console_Output.sync_file_range02-debug-hw.log)
[Standard_Console_Output mount06-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073471/Standard_Console_Output.mount06-debug-hw.log)
[Standard_Console_Output unshare01-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073472/Standard_Console_Output.unshare01-debug-hw.log)
[Standard_Console_Output lgetxattr02-debug-hw.log](https://github.com/lsds/sgx-lkl/files/5073473/Standard_Console_Output.lgetxattr02-debug-hw.log)

**Comment by SeanTAllen** [comment]
fallocate01 passes for me locally with latest oe_port and latest sgx-lkl branch of ltp.

**Comment by hukoyu** [comment]
After getting the latest code and ltp submodule with PR https://github.com/lsds/sgx-lkl/pull/793 all of these tests passed.
