### ISSUE TITLE
Not clear if miniport sample fails or passes

### ISSUE THREAD

**Issue by lshacham** [lsds/sgx-lkl#8]
I run make at sgx-lkl/apps/miniroot

I then run: 
sudo SGXLKL_TAP=sgxlkl_tap0 SGXLKL_VERBOSE=1 ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /usr/bin/redis-server --bind 10.0.1.1

The output:

[ 0.000000] Linux version 4.10.0+ (sem@sem) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #2 Mon Apr 23 14:25:43 EET 2018
[ 0.000000] bootmem address range: 0x480f000 - 0x540e000
[ 0.000000] Built 1 zonelists in Zone order, mobility grouping off. Total pages: 3029
[ 0.000000] Kernel command line: virtio_mmio.device=292@0x1000000:1 virtio_mmio.device=268@0x2000000:2
[ 0.000000] PID hash table entries: 64 (order: -3, 512 bytes)
[ 0.000000] Dentry cache hash table entries: 2048 (order: 2, 16384 bytes)
[ 0.000000] Inode-cache hash table entries: 1024 (order: 1, 8192 bytes)
[ 0.000000] Memory available: 11988k/0k RAM
[ 0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[ 0.000000] NR_IRQS:4096
[ 0.000000] lkl: irqs initialized
[ 0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[ 0.000254] lkl: time and timers initialized (irq3)
[ 0.000317] pid_max: default: 4096 minimum: 301
[ 0.000378] Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
[ 0.000379] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
[ 0.002107] devtmpfs: initialized
[ 0.006839] console [lkl_console0] enabled
[ 0.006902] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[ 0.007039] NET: Registered protocol family 16
[ 0.008537] clocksource: Switched to clocksource lkl
[ 0.009269] NET: Registered protocol family 2
[ 0.009463] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[ 0.009467] TCP bind hash table entries: 512 (order: 0, 4096 bytes)
[ 0.009471] TCP: Hash tables configured (established 512 bind 512)
[ 0.009539] UDP hash table entries: 128 (order: 0, 4096 bytes)
[ 0.009543] UDP-Lite hash table entries: 128 (order: 0, 4096 bytes)
[ 0.009620] NET: Registered protocol family 1
[ 0.009696] virtio-mmio: Registering device virtio-mmio.0 at 0x1000000-0x1000123, IRQ 1.
[ 0.009771] virtio-mmio: Registering device virtio-mmio.1 at 0x2000000-0x200010b, IRQ 2.
[ 0.010461] workingset: timestamp_bits=62 max_order=12 bucket_order=0
[ 0.014522] io scheduler noop registered
[ 0.014528] io scheduler deadline registered
[ 0.014591] io scheduler cfq registered (default)
[ 0.014654] virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA. Trying to continue, but this might not work.
[ 0.014706] virtio-mmio virtio-mmio.1: Failed to enable 64-bit or 32-bit DMA. Trying to continue, but this might not work.
[ 0.030019] mousedev: PS/2 mouse device common for all mice
[ 0.030310] NET: Registered protocol family 10
[ 0.030714] Segment Routing with IPv6
[ 0.030739] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[ 0.031071] Warning: unable to open an initial console.
[ 0.031134] This architecture does not have kernel memory protection.
[ 0.032332] EXT4-fs (vda): mounted filesystem with ordered data mode. Opts:
[ 0.042897] random: host1: uninitialized urandom read (19 bytes read)
[ 0.042908] random: host1: uninitialized urandom read (1024 bytes read)
1:M 23 Apr 12:32:02.009 * Increased maximum number of open files to 10032 (it was originally set to 1024).
.
.-__ ''-._ _.- .. ''-._ Redis 3.2.11 (8e1aef66/0) 64 bit
.-.-```. ```\/ _.,_ ''-._ ( ' , .-` | `, ) Running in standalone mode |`-._`-...-` __...-.-.|'_.-'| Port: 6379 |-. ._ / _.-' | PID: 1-._ -._-./ .-' .-'
|-._-. -.__.-' _.-'_.-'| |-.-._ _.-'_.-' | http://redis.io-._ -._-..-'.-' .-'
|-._-. -.__.-' _.-'_.-'| |-.-._ _.-'_.-' |-._ -._-..-'_.-' _.-'
-._-..-' _.-'
-._ _.-'-..-'

1:M 23 Apr 12:32:02.010 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 23 Apr 12:32:02.010 # Server started, Redis version 3.2.11
1:M 23 Apr 12:32:02.010 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 23 Apr 12:32:02.010 * The server is now ready to accept connections on port 6379
write to fd netdev fails: No error information
[ 1.978632] random: fast init done

On a different terminal I run:

sudo redis-cli -h 10.0.1.1

The output:

Could not connect to Redis at 10.0.1.1:6379: Connection timed out
not connected>

**Comment by lshacham** [comment]
**Summary**: Issue fixed. 

**Details**: 

The reason I got: 

`write to fd netdev fails: No error information`

Is because I did not run the commands for a TAP interface on the host. 

**Notice**:  the Helloworld-java sample worked without the TAP interface. 
I recommend adding clarification to README.md that TAP is only required for solutions that use network. 

**Result of a successful run**: 

On the first terminal I run: 

`sudo SGXLKL_TAP=sgxlkl_tap0 ../../build/sgx-lkl-run ./sgxlkl-miniroot-fs.img /usr/bin/redis-server --bind 10.0.1.1`

And get: 

```
1:M 24 Apr 06:43:15.583 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.2.11 (8e1aef66/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 24 Apr 06:43:15.584 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 24 Apr 06:43:15.584 # Server started, Redis version 3.2.11
1:M 24 Apr 06:43:15.584 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 24 Apr 06:43:15.584 * The server is now ready to accept connections on port 6379
```

On the other terminal I run: 

`sudo redis-cli -h 10.0.1.1` 

And get: 

`10.0.1.1:6379> `

I write: 

`ping`

and get: 

`PONG`

**Comment by cpriebe** [comment]
Thanks Liron,

sgx-lkl-java doesn't require a tap interface to exist by default anymore now. I am quoting my comment from issue #5 for completeness:

"SGX-LKL generally does not have to be run as superuser. I have done a few tests, and without superuser rights, execution should fail early on with an error message indicating that the specified network interface is unavailable on the host (either because it is missing completely or because the current user does not have permissions to use it). Unfortunately the corresponding `ioctl` call does not fail when run as superuser, which is why the error currently does not occur when running SGX-LKL under `sudo`. We are looking into fixing this."
