### ISSUE TITLE
Assertion failed error when running sgx-lkl-run

### ISSUE THREAD

**Issue by ppourali** [lsds/sgx-lkl#80]
Hello, 

I am trying to run an image using the sgx-lkl-run but it throws the following error:

sgx-lkl-run: attestation/aesm.c:112: init_quote_response: Assertion `qr->has_targetinfo' failed.
Aborted (core dumped)

No matter what image I run, it throws this error even for the sample images given in the repo. My SGX service is also up and running (I assume since I can successfully run the attestation example given in IntelSGX git repo).

I didn't have this issue before when I was using another machine, though.
Any help would be appreciated.

Thanks,
Parsa

**Comment by cpriebe** [comment]
Hi @ppourali,

Thanks for reporting this. We have received similar reports in the past but I am not entirely sure yet what causes this. (Re-)installing the latest driver and PSW (libsgx-enclave-common) seems to have helped at least in some cases. It might be worth to try that first.

Apart from that could you report your system configuration and which version of the driver and PSW you currently have installed?

Thanks!

**Comment by ppourali** [comment]
Thanks for the reply. I tried to reinstall PSW (I have the /opt/intel/libsgx-enclave-common folder and seems to be working properly) but no luck! 

Configurations: Ubuntu 16.04, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz,  SGX 2.0 Linux Driver, 
SGX-LKL version 1.0.0 Hardware Mode.

**Comment by ppourali** [comment]
OK, it works only when I install the sgx-lkl in simulation mode. Not sure, why Hardware mode throws the error though.

**Comment by cpriebe** [comment]
The error is related to the AESM service (installed as part of the PSW/libsgx-enclave-common). SGX-LKL talks to the service to initialise a quote for remote attestation. This only applies to hardware mode so you won't see the same error in simulation mode.

Technically, the quote is only relevant if you actually want to perform remote attestation so we might want to change the assertion here into a warning instead saying that remote attestation will be unavailable.

Version 2.0 of the SGX driver is pretty old. The current version is 2.6 (https://download.01.org/intel-sgx/sgx-linux/2.7/distro/ubuntu16.04-server/).

**Comment by ppourali** [comment]
I see, Thanks for the info :)
