### ISSUE TITLE
branch cleanup-musl deleted ?

### ISSUE THREAD

**Issue by flo-th** [lsds/sgx-lkl#840]
Hi all,

To be able to compile the project sgx-spark, i need to clone the code from the branch cleanup-musl, but it seems deleted.
Has it been merged or renamed ?

Thanks in advance,

Flo

**Comment by prp** [comment]
Hi @flothia, the non Open Enclave version of SGX-LKL has been deprecated, so you would have to try to migrate sgx-spark to the latest master version of SGX-LKL.

**Comment by flo-th** [comment]
Hi @prp,

Thanks for your answer.
The compilation of the branch oe_port succeed for me on Ubuntu 16.04.
