### ISSUE TITLE
Can SGX-LKL interact with image's outsid world to store retrieve from a shared memory?

### ISSUE THREAD

**Issue by ppourali** [lsds/sgx-lkl#85]
Hi there,

Let's say we run two pieces of code on the same machine. Can the code inside SGX read/write from/to a shared memory that is accessible for both pieces of code? I think at the moment the memory that is being written by SGX image is not accessible by the processes outside the SGX.
i.e., 
SGX-Image_Code Read/Write ===>  **SHARED MEMORY** <=== Outside SGX_Code Read/Write

One way of doing this is passing messages through sockets! However, it comes with an overhead which reduces the performance!

Thanks,
Parsa

**Comment by cpriebe** [comment]
Apologies for the delay. SGX-LKL right now does not support shared memory. SGX-LKL aims to run single-process application with minimal reliance on the host system, so we try to minimise any interaction with the host. Also, we have focused on supporting unmodified applications. Such a shared memory abstraction would most likely require corresponding application changes.

That said, SGX-LKL can't prevent applications from accessing untrusted memory directly, so if you can make your application aware of the shared memory region, it shouldn't be too difficult to implement what you need on top of SGX-LKL.
