### ISSUE TITLE
How does SGX-LKL support jvm GC safepoint mechanism please?

### ISSUE THREAD

**Issue by superajun-wsj** [lsds/sgx-lkl#86]
As we know, before JVM triggle a GC, it will STW by safepoint mechanism, but memory in Enclaves is always 'rw' priority in version 1, it means instruct “test   %eax,0x160100” should never
trigger a signal, right? if so, how to STW in time please?

**Comment by prp** [comment]
With SGX version 1, we permit applications such as the JVM to do mprotect host calls to change page permissions. If the STW GC triggers a page fault, this is delivered to a handler inside of the enclave.

**Comment by superajun-wsj** [comment]
@prp , Thanks very much for your response first. do you mean we could change page permissions in enclaves by host calling with SGX version 1?  do we need to make any changes towards OpenJDK please? I don't understand how could jvm trigger a signal by instruct "test %eax" in enclaves?

**Comment by prp** [comment]
No, there are no changes required. It works transparently because SGX-LKL delivers the page fault that is raised by the host OS to the JVM inside the enclave.
