### ISSUE TITLE
Is WireGuard IPSec endpoint inside Intel SGX enclave? 

### ISSUE THREAD

**Issue by markueni** [lsds/sgx-lkl#87]
Hi,

I have a scenario in which I have one server machine and one client machine. Up to now I run RAP between server and client machine and then I setup an IPSEC tunnel (using Strongswan)between client and enclave in order to transfer packets and then I placed endpoint of IPSEC tunnel inside enclave. That works but I do not want to use Wireguard since it is faster than Strongswan. The problem is that I do not know a lot about Wireguard and I have seen that you already have managed to integrate Wireguard on your  enclave but I am not sure wether the IPSEC endpoint is inside enclave  in your project or not?
 If that is right, then is it possible to integrate that part to my sgx application?
I would really appreciate a feedback

**Comment by cpriebe** [comment]
Hi @markueni,

Just to clarify, IPSEC and Wireguard are completely independent and don't really have anything to do with each other, other than sharing similar use cases.

The Wireguard endpoint is inside the enclave, yes. Every SGX-LKL instance sets up a Wireguard interface inside the enclave and generates a random key at startup. The public key is attached to the attestation report. You can find more info in the wiki on [network encryption](https://github.com/lsds/sgx-lkl/wiki/Network-encryption) and [remote attestation](https://github.com/lsds/sgx-lkl/wiki/Remote-Attestation-and-Remote-Control).
