### ISSUE TITLE
How to check the interfaces of the Enclave in case you created an encrypted disk

### ISSUE THREAD

**Issue by kleirama** [lsds/sgx-lkl#89]
Hi,

I am trying to check the interfaces of the Enclave but I am not able to do that.

When I run on the Server machine which hosts the enclave
> xxd -p -c 512 disk.img.key

I got the output below

>d5369d0b761612ff6616c551d71fee0f386d8564a2797449f8fcfba492dc01d50187f3e56f0943d6012da0df792005ae7336b452e8c39ae32a9f40d5b9e31d14

Then I run the command below in order to check the interfaces of the Enclave

> SGXLKL_TAP=sgxlkl_tap0 SGXLKL_HD_KEY="d5369d0b761612ff6616c551d71fee0f386d8564a2797449f8fcfba492dc01d50187f3e56f0943d6012da0df792005ae7336b452e8c39ae32a9f40d5b9e31d14" ./build/sgx-lkl-run ./disk.img /sbin/ifconfig

I got the error below

> Error: Unable to activate encrypted disk. Please ensure you have provided the correct passphrase/keyfile!

This error does not make sense to me since I guess I have provided the right HEX passphrase.
Note: I have created the disk.img on client machine and then trasnfer via scp disk.img and disk.img.key to the Server machine.

I also tried to run the command with filename instead of its value as below:

> SGXLKL_TAP=sgxlkl_tap0  SGXLKL_HD_KEY=disk.img.key ./build/sgx-lkl-run ./disk.img /sbin/ifconfig

But i still got an error like: 

> [    SGX-LKL   ] Error: Error: lkl_mount_blockdev()=Invalid argument (-22)

Am I doing something wrong?

**Comment by cpriebe** [comment]
Hi @kleirama,

I don't see anything wrong with your example. Could you try and see if this also happens to you with a minimal example (e.g. without copying the disk image or keys around):

```
$:~/dev/sgx-lkl$ ./tools/sgx-lkl-disk create --size=100M --encrypt --key-file --alpine="" disk.img
[...]
$: ~/dev/sgx-lkl$ SGXLKL_HD_KEY=./disk.img.key ./build/sgx-lkl-run ./disk.img /bin/ls /
bin         dev         etc         home        lib         lost+found  media       mnt         opt         proc        root        run         sbin        srv         sys         tmp         usr         var
```

If that does work, maybe something went wrong when copying the disk image or key?
